kind: storage_link
schema:
  url: "umodel.aliyun.com"
  version: "v1.0.0"
metadata:
  name: "infra.node.metrics_to_prometheus"
  domain: infra
  display_name:
    en_us: "Node metrics stored in Prometheus"
    zh_cn: "节点指标存储在 Prometheus"
spec:
  src:
    domain: infra
    kind: metric_set
    name: infra.node.metrics
  dest:
    domain: infra
    kind: prometheus
    name: localization.prometheus.core
  fields_mapping:
    target_id: target_id
    environment: environment
