# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - clickhouse Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class ClickhouseV100(UModelCoreObject):
    """clickhouse class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # ClickHouse 的核心配置部分。UModel 只使用这些字段生成 SQL 查询计划，不直接执行查询，也不保存明文凭据。
    spec: Optional['ClickhouseV100Spec'] = None

    def get_kind(self) -> str:
        return 'clickhouse'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class ClickhouseV100Spec:
    """ClickHouse 的核心配置部分。UModel 只使用这些字段生成 SQL 查询计划，不直接执行查询，也不保存明文凭据。"""
    # 该存储渲染所用的查询家族。设为 sql-table 即可经由 sql-table 渲染器把 get_metrics 渲染为 SQL；不设则该存储仅透传、不渲染。该家族此后的每个后端都只是配置。
    family: Optional[str] = None
    # ClickHouse 的访问地址，例如 http://clickhouse:8123。
    endpoint: Optional[str] = None
    # 查询所用的数据库名。
    database: Optional[str] = None
    # 指标所在的表名。sql-table 渲染器从该表 SELECT 数据。
    table: Optional[str] = None
    # 时间列名，用于时间范围过滤与降采样。默认值为 timestamp。
    time_column: Optional[str] = None
    # 指标数值列名。默认值为 value。
    value_column: Optional[str] = None
    # 指标名所在的列名，用于按指标过滤。默认值为 metric_name。
    metric_column: Optional[str] = None
    # 默认查询类型。instant 表示取最新值，range 表示区间降采样。
    default_query_type: Optional[str] = None
    # 区间查询的默认降采样步长，例如 60s、1m。
    default_step: Optional[str] = None
    # 凭据引用标识，例如 secret://clickhouse-prod-readonly。不得在 UModel 中保存明文用户名、密码或 Token。
    credential_ref: Optional[str] = None
    # 是否校验 TLS 证书。默认值为 true。
    tls_verify: Optional[bool] = None
    # ClickHouse 的额外非敏感配置，以键值对形式存储。
    properties: Optional[Dict[str, str]] = None
    # 用于标注该 ClickHouse 存储的标签。
    tags: Optional[Dict[str, str]] = None
