# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - elasticsearch Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class ElasticsearchV100(UModelCoreObject):
    """elasticsearch class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # Elasticsearch 的核心配置部分。UModel 只使用这些字段生成 Elasticsearch 查询计划，不直接执行查询，也不保存明文凭据。
    spec: Optional['ElasticsearchV100Spec'] = None

    def get_kind(self) -> str:
        return 'elasticsearch'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class ElasticsearchV100Spec:
    """Elasticsearch 的核心配置部分。UModel 只使用这些字段生成 Elasticsearch 查询计划，不直接执行查询，也不保存明文凭据。"""
    # Elasticsearch 集群访问地址，例如 https://es.example.com:9200。
    endpoint: Optional[str] = None
    # 默认查询索引名称，也可以是 Elasticsearch 支持的索引通配表达式。
    index: Optional[str] = None
    # 面向按时间滚动索引的索引模式，例如 logs-${yyyy.MM.dd}。如果为空，查询规划使用 index 字段。
    index_pattern: Optional[str] = None
    # Elasticsearch 版本号或版本族，例如 7.x、8.x。
    version: Optional[str] = None
    # 查询生成方言。默认生成 Elasticsearch Query DSL。
    query_dialect: Optional[str] = None
    # 时间过滤字段名，用于将请求时间范围下推到 Elasticsearch 查询中。
    time_field: Optional[str] = None
    # 未显式指定 limit 时生成查询的默认 size。
    default_size: Optional[int] = None
    # 查询规划允许生成的最大 size，用于避免生成过大的查询计划。
    max_size: Optional[int] = None
    # 可选的 Elasticsearch routing 值。用于规划需要固定 routing 的查询。
    routing: Optional[str] = None
    # 凭据引用标识，例如 secret://es-prod-readonly。不得在 UModel 中保存明文用户名、密码或 Token。
    credential_ref: Optional[str] = None
    # 是否校验 TLS 证书。默认值为 true。
    tls_verify: Optional[bool] = None
    # 非敏感 HTTP 头，用于租户、路由等查询上下文。不得存放认证密钥。
    headers: Optional[Dict[str, str]] = None
    # Elasticsearch 的额外非敏感配置，以键值对形式存储。
    properties: Optional[Dict[str, str]] = None
    # 用于标注该 Elasticsearch 存储的标签。
    tags: Optional[Dict[str, str]] = None
