# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - 共享类型定义
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
@dataclass
class ConstraintTypeV1Enum:
    """枚举值列表"""
    values: Optional[List[Any]] = None
    # 默认值
    default_value: Optional[str] = None

@dataclass
class ConstraintTypeV1Array:
    """数组约束定义，内部的 item 可以嵌套定义 metadata_properties，也支持特殊引用规则 "type_ref"。"""
    item: Optional[Dict[str, Any]] = None
    min_size: Optional[float] = None
    max_size: Optional[float] = None

@dataclass
class ConstraintTypeV1AdvancedExpressionLeft:
    """左操作数，可以是字段引用或字面值"""
    type: Optional[str] = None
    # 具体值或字段路径
    value: Optional[str] = None

@dataclass
class ConstraintTypeV1AdvancedExpressionRight:
    """右操作数，可以是字段引用或字面值"""
    type: Optional[str] = None
    # 具体值或字段路径
    value: Optional[str] = None

@dataclass
class ConstraintTypeV1AdvancedExpression:
    """约束表达式，支持逻辑操作符和字段引用"""
    # 逻辑操作符
    operator: Optional[str] = None
    # 条件列表，支持嵌套逻辑表达式
    conditions: Optional[List[Dict[str, Any]]] = None
    # 左操作数，可以是字段引用或字面值
    left: Optional['ConstraintTypeV1AdvancedExpressionLeft'] = None
    # 右操作数，可以是字段引用或字面值
    right: Optional['ConstraintTypeV1AdvancedExpressionRight'] = None

@dataclass
class ConstraintTypeV1Advanced:
    """高级约束定义，用于支持更复杂的约束条件，包括逻辑操作和字段引用。 主要功能： 1. 支持逻辑操作符：and, or, not, eq, ne, gt, ge, lt, le, in, nin, exists, regex 2. 支持字段路径引用： -..."""
    # 约束表达式，支持逻辑操作符和字段引用
    expression: Optional['ConstraintTypeV1AdvancedExpression'] = None

@dataclass
class AutomationConfigV1Trigger:
    """触发条件配置。"""
    # 触发条件类型，如 scheduled（定期触发）、event（事件触发）、custom（自定义触发）等。
    trigger_type: Optional[str] = None
    # 触发条件相关属性配置，根据type类型自由扩展。
    properties: Optional[Dict[str, str]] = None

@dataclass
class SkillConfigV1FilesItem:
    """SkillConfigV1FilesItem inline class"""
    # 文件名称，包含相对路径（如 SKILL.md、scripts/extract.py、references/REFERENCE.md）。
    name: Optional[str] = None
    # 文件内容。
    content: Optional[str] = None

@dataclass
class LinkV1Src:
    """源 Set 的标识。值不能为空。"""
    # 源 Set 的域。
    domain: Optional[str] = None
    # 源 Set 的类型。值不能为空。
    kind: Optional[str] = None
    # 源 Set 的名称。值不能为空。
    name: Optional[str] = None
    # 对于源 Set 的过滤器，用于部分 Link 的场景，例如 EntitySet 中只有"region=cn-beijing"的实体存在此关联。该方式已废弃，请使用 filter_by_entity 替代。
    filter: Optional[str] = None

@dataclass
class LinkV1Dest:
    """目标 Set 的标识。值不能为空。"""
    # 目标 Set 的域。
    domain: Optional[str] = None
    # 目标 Set 的类型。值不能为空。
    kind: Optional[str] = None
    # 目标 Set 的名称。值不能为空。
    name: Optional[str] = None

@dataclass
class KnowledgeConfigV1ApplyPolicy:
    """知识如何应用的配置。"""
    # 应用策略，如auto（自动）、manual（手动）、always（总是）、custom（自定义）等。
    apply_type: Optional[str] = None
    # 应用相关属性配置，根据 custom 类型自由扩展。
    properties: Optional[Dict[str, str]] = None

@dataclass
class ObservationV1Phenomenon:
    """现象定义，描述要观察什么以及如何观察。"""
    # 现象类型，如query（查询）、action（动作）、dashboard（大盘）、event（事件）等。
    phenomenon_type: Optional[str] = None
    # 现象相关输入配置，用于指引上层如何选择默认的参数进行填入。包括 Dashboard 变量、Query 输入参数等
    inputs: Optional[List[Optional['ParameterConfigV1']]] = None
    # 可选，现象相关输出配置，用于指引上层如何解析查询结果。
    outputs: Optional[List[Optional['ParameterConfigV1']]] = None
    # 现象相关属性配置，根据 type 类型自由扩展。
    properties: Optional[Dict[str, str]] = None

@dataclass
class ObservationV1ConclusionsItem:
    """ObservationV1ConclusionsItem inline class"""
    # 结论生效条件类型，根据现象类型，条件执行方式不同。可以是 query/action 执行结果后的 bool 表达式计算，也可以是由 LLM 进行判断的 prompts。
    condition_type: Optional[str] = None
    # 结论生效条件，根据现象类型，条件执行方式不同。
    condition: Optional[str] = None
    # 结论严重程度。
    severity: Optional[str] = None
    # 结论显示名称。
    display_name: Optional['SemanticStringV1'] = None
    # 结论简短描述。
    short_description: Optional['SemanticStringV1'] = None
    # 结论详细描述。
    description: Optional['SemanticStringV1'] = None
    # 结论分组。在同一个结论分组下，只返回最高等级的结论。
    group: Optional[str] = None
    # 结论相关属性配置。
    properties: Optional[Dict[str, str]] = None

@dataclass
class MetadataV1CommonSchemaInfo:
    """背景：在阿里云可观测业务使用中，内置的UModel数据会作为公共UModel（CommonSchema）默认存在，公共UModel数据以引用方式（CommonSchemaRef）配置在UModel，在查询时动态生成UModel实例并附加该字段作为额外..."""
    # CommonSchema的Group信息
    group: Optional[str] = None
    # CommonSchema的版本号
    version: Optional[str] = None


if TYPE_CHECKING:
    from .base_types import UModelObject, SemanticString
else:
    from .base_types import UModelObject, SemanticString

@dataclass
class SemanticStringV1(UModelObject):
    """支持多语言的语义字符串类型，可以是简单字符串或多语言对象"""
    # 中文描述
    zh_cn: Optional[str] = None
    # 英文描述
    en_us: Optional[str] = None

    def get_kind(self) -> str:
        return 'semantic_string'

@dataclass
class ConstraintTypeV1(UModelObject):
    """约束条件属性定义"""
    # 是否为必填字段
    required: Optional[bool] = None
    # 默认值，需要和 type 类型匹配。
    default_value: Optional[Any] = None
    # 正则表达式模式
    pattern: Optional[str] = None
    # 最小长度
    min_len: Optional[float] = None
    # 最大长度
    max_len: Optional[float] = None
    # 枚举值列表
    enum: Optional['ConstraintTypeV1Enum'] = None
    # 数组约束定义，内部的 item 可以嵌套定义 metadata_properties，也支持特殊引用规则 "type_ref"。
    array: Optional['ConstraintTypeV1Array'] = None
    # Map约束定义，内部的 key 和 value 可以嵌套定义 metadata_properties，也支持特殊引用规则 "type_ref"。
    map: Optional[Dict[str, Any]] = None
    # 多类型约束定义，即该字段可以有多种类型，例如支持 number 和 array[number]。其中每个元素为一个单独的类型定义。
    oneOf: Optional[List[Any]] = None
    # 高级约束定义，用于支持更复杂的约束条件，包括逻辑操作和字段引用。 主要功能： 1. 支持逻辑操作符：and, or, not, eq, ne, gt, ge, lt, le, in, nin, exists, regex 2. 支持字段路径引用： -...
    advanced: Optional['ConstraintTypeV1Advanced'] = None

    def get_kind(self) -> str:
        return 'constraint_type'

@dataclass
class AutomationConfigV1(UModelObject):
    """automation_config class"""
    # 自动化项名称，在同一个RunbookSet中必须唯一。
    name: Optional[str] = None
    # 自动化项显示名称。
    display_name: Optional['SemanticStringV1'] = None
    # 自动化项简短描述。
    short_description: Optional['SemanticStringV1'] = None
    # 自动化项详细描述信息。
    description: Optional['SemanticStringV1'] = None
    # 自动化类型，如action、script、webhook等。
    automation_type: Optional[str] = None
    # 触发条件配置。
    trigger: Optional['AutomationConfigV1Trigger'] = None
    # 自动化项属性配置。
    properties: Optional[Dict[str, str]] = None
    # 自动化项标签。
    tags: Optional[Dict[str, str]] = None

    def get_kind(self) -> str:
        return 'automation_config'

@dataclass
class SkillConfigV1(UModelObject):
    """skill_config class"""
    # 技能名称（唯一标识），仅支持小写字母、数字和连字符，不能以连字符开头或结尾，不能包含连续连字符。
    name: Optional[str] = None
    # 技能显示名称。
    display_name: Optional['SemanticStringV1'] = None
    # 技能描述，说明技能的功能和使用场景，帮助 Agent 识别何时使用该技能。
    description: Optional['SemanticStringV1'] = None
    # 技能的许可证信息。
    license: Optional[str] = None
    # 技能的环境兼容性要求，如依赖的系统包、网络访问需求等。
    compatibility: Optional[str] = None
    # 预授权工具列表，空格分隔的工具标识符。
    allowed_tools: Optional[str] = None
    # 技能的额外元数据，如作者、版本等。
    metadata: Optional[Dict[str, str]] = None
    # 技能标签，用于分类和检索。
    tags: Optional[Dict[str, str]] = None
    # 技能文件列表，包含 SKILL.md 及其他辅助文件（如 scripts/、references/、assets/ 下的文件）。
    files: Optional[List[Optional['SkillConfigV1FilesItem']]] = None
    # 技能包的外部URL地址（如OSS地址），与files字段二选一。当使用URL时，技能文件从该地址加载。
    skill_url: Optional[str] = None
    # 技能优先级，用于排序和选择。值越小优先级越高。
    priority: Optional[int] = None
    # 最后更新时间。
    last_updated: Optional[datetime] = None

    def get_kind(self) -> str:
        return 'skill_config'

@dataclass
class ToolkitV1(UModelObject):
    """toolkit class"""
    # 工具箱名称，在同一个 RunbookSet 内必须唯一。
    name: Optional[str] = None
    # 工具箱显示名称。
    display_name: Optional['SemanticStringV1'] = None
    # 工具箱简短描述。
    short_description: Optional['SemanticStringV1'] = None
    # 工具箱详细描述信息。
    description: Optional['SemanticStringV1'] = None
    # 工具箱类型，如 mcp、pop_api、api_call、script、webhook 等。
    toolkit_type: Optional[str] = None
    # 运行时配置，如连接信息、认证、超时等，Toolkit 内所有 Tool 继承使用。
    configs: Optional[Dict[str, Any]] = None
    # 扩展元数据，描述性属性，自由扩展的 k-v。
    properties: Optional[Dict[str, str]] = None
    # 共享标签。
    tags: Optional[Dict[str, str]] = None
    # 工具列表。
    tools: Optional[List[Optional['ToolV1']]] = None

    def get_kind(self) -> str:
        return 'toolkit'

@dataclass
class FieldSpecV1(UModelObject):
    """field_spec class"""
    # Field 在 UModel 系统中的名称。值不能为空。值格式为小写字母数字字符。
    name: Optional[str] = None
    # Field 在 UModel 系统中的显示名称。值不能为空。
    display_name: Optional['SemanticStringV1'] = None
    # Field 在 UModel 系统中的描述。
    description: Optional['SemanticStringV1'] = None
    # Field 在 UModel 系统中的简短描述。
    short_description: Optional['SemanticStringV1'] = None
    # 元素的发布阶段。默认值为 preview。
    launch_stage: Optional[str] = None
    # 字段的类型。值必须是以下之一：string、integer、float、boolean、time、json_object、json_array。值不能为空。
    type: Optional[str] = None
    # 对于枚举值的映射和解释，为了更好的展示映射值含义，对于 mapping 的 value 字段单独定义，value 包含4个字段："name"、"display_name"、"description"和"short_description"。例如，"s...
    value_mapping: Optional[Dict[str, Optional['ValueMappingV1']]] = None
    # 指标的单位，值格式为字符串。 注意：单位仅用于展示，不会进行格式转换，例如 ms 不会自动根据大小转换为 s。 最佳实践：首先配置 data_format ，在大部分可观测场景下，data_format 即可满足需求，unit 填写为空即可。 若不满...
    unit: Optional[str] = None
    # 指标的格式化方式，值格式为字符串。支持的格式化选项： 数值格式化： - KMB: 千、百万、十亿格式化，样例：K,Mil,Bil - milli: 处理为毫秒格式，样例：1,000,000 存储格式化： - byte: 处理为字节格式，样例：B/KB...
    data_format: Optional[str] = None
    # 用于表示字段是否可分析，即作为Group By的列。默认值为false。
    analysable: Optional[bool] = None
    # 用于表示字段是否可过滤，即支持索引过滤。默认值为false。
    filterable: Optional[bool] = None
    # 用于表示字段是否可排序。默认值为false。
    orderable: Optional[bool] = None
    # 用于表示字段的默认排序顺序。值必须是以下之一：asc、desc。默认值为asc。
    default_order: Optional[str] = None
    # 正则表达式，用于定义字段的值范围（字符串）。
    pattern: Optional[str] = None
    # 字符串值的最大长度。仅适用于字符串类型。
    max_length: Optional[int] = None
    # 字段值的示例。值可以为空。
    example: Optional[Any] = None
    # 字段的最大值。值可以为空。仅适用于整数和浮点类型。
    max_value: Optional[float] = None
    # 字段的最小值。值可以为空。仅适用于整数和浮点类型。
    min_value: Optional[float] = None
    # 字段的默认值。值可以为空。
    default_value: Optional[Any] = None
    # Field 在 UModel 系统中的图标。值格式为'url'。
    icon: Optional[str] = None
    # 用于表示该字段唯一标识。
    uri: Optional[str] = None
    # 用于表示该 Field 的标签。
    tags: Optional[Dict[str, str]] = None
    # 用于表示该 Field 的附加属性。
    properties: Optional[Dict[str, str]] = None

    def get_kind(self) -> str:
        return 'field_spec'

@dataclass
class LinkV1(UModelObject):
    """link class"""
    # 源 Set 的标识。值不能为空。
    src: Optional['LinkV1Src'] = None
    # 目标 Set 的标识。值不能为空。
    dest: Optional['LinkV1Dest'] = None
    # 在部分Entity具备的Link中，用于标识这部分Entity的过滤条件。
    filter_by_entity: Optional[str] = None
    # Link 的优先级。值可以为空。默认值为5。
    priority: Optional[int] = None

    def get_kind(self) -> str:
        return 'link'

@dataclass
class ValueMappingV1(UModelObject):
    """value_mapping class"""
    # 在 UModel 系统中的名称。值不能为空。值格式为小写字母数字字符。
    name: Optional[str] = None
    # 在 UModel 系统中的显示名称。值不能为空。
    display_name: Optional['SemanticStringV1'] = None
    # 在 UModel 系统中的描述。
    description: Optional['SemanticStringV1'] = None
    # 在 UModel 系统中的简短描述。
    short_description: Optional['SemanticStringV1'] = None

    def get_kind(self) -> str:
        return 'value_mapping'

@dataclass
class KnowledgeConfigV1(UModelObject):
    """knowledge_config class"""
    # 知识项名称，在同一个RunbookSet中必须唯一。
    name: Optional[str] = None
    # 知识项显示名称。
    display_name: Optional['SemanticStringV1'] = None
    # 知识项简短描述。
    short_description: Optional['SemanticStringV1'] = None
    # 知识项详细描述信息。
    description: Optional['SemanticStringV1'] = None
    # 知识如何应用的配置。
    apply_policy: Optional['KnowledgeConfigV1ApplyPolicy'] = None
    # 内容类型，支持markdown、html、url、pdf等。UModel 内置支持的类型为 markdown。
    content_type: Optional[str] = None
    # 知识内容，根据content_type可以是文本内容或URL地址。
    content: Optional[str] = None
    # 知识内容的外部URL地址。
    content_url: Optional[str] = None
    # 知识项优先级，用于排序显示以及模型推理时选择。
    priority: Optional[int] = None
    # 最后更新时间。
    last_updated: Optional[datetime] = None
    # 知识项标签。
    tags: Optional[Dict[str, str]] = None

    def get_kind(self) -> str:
        return 'knowledge_config'

@dataclass
class ActionConfigV1(UModelObject):
    """action_config class"""
    # 操作名称，在同一个RunbookSet中必须唯一。
    name: Optional[str] = None
    # 操作显示名称。
    display_name: Optional['SemanticStringV1'] = None
    # 操作简短描述。
    short_description: Optional['SemanticStringV1'] = None
    # 操作详细描述信息。
    description: Optional['SemanticStringV1'] = None
    # 操作类型，例如pop_api、mcp、api_call、script、webhook等。
    action_type: Optional[str] = None
    # 操作参数配置列表。
    inputs: Optional[List[Optional['ParameterConfigV1']]] = None
    # 操作输出配置列表。
    outputs: Optional[List[Optional['ParameterConfigV1']]] = None
    # 是否需要确认才能执行操作。
    confirmation_required: Optional[bool] = None
    # 操作的风险等级。
    risk_level: Optional[str] = None
    # 详细配置信息，用于配置不同类型操作的详细信息
    properties: Optional[Dict[str, str]] = None
    # 操作标签。
    tags: Optional[Dict[str, str]] = None

    def get_kind(self) -> str:
        return 'action_config'

@dataclass
class ToolParameterConfigV1(UModelObject):
    """tool_parameter_config class"""
    # 参数属性定义，键为参数名称，值为参数定义对象。
    properties: Optional[Dict[str, Any]] = None
    # 必填参数名称列表。
    required: Optional[List[str]] = None

    def get_kind(self) -> str:
        return 'tool_parameter_config'

@dataclass
class ParameterConfigV1(UModelObject):
    """parameter_config class"""
    # 参数名称。
    name: Optional[str] = None
    # 参数显示名称。
    display_name: Optional['SemanticStringV1'] = None
    # 参数描述信息。
    description: Optional['SemanticStringV1'] = None
    # 参数类型。
    type: Optional[str] = None
    # 是否为必填参数。
    required: Optional[bool] = None
    # 参数默认值。
    default: Optional[str] = None

    def get_kind(self) -> str:
        return 'parameter_config'

@dataclass
class MetricV1(UModelObject):
    """metric class"""
    # 指标的名称。值不能为空。
    name: Optional[str] = None
    # 指标的显示名称。
    display_name: Optional['SemanticStringV1'] = None
    # 指标的描述。值格式为语义字符串。
    description: Optional['SemanticStringV1'] = None
    # 指标的简短描述。值格式为语义字符串。
    short_description: Optional['SemanticStringV1'] = None
    # 元素的发布阶段。默认值为 preview。
    launch_stage: Optional[str] = None
    # 指标的单位，值格式为字符串。 注意：单位仅用于展示，不会进行格式转换，例如 ms 不会自动根据大小转换为 s。 最佳实践：首先配置 data_format ，在大部分可观测场景下，data_format 即可满足需求，unit 填写为空即可。 若不满...
    unit: Optional[str] = None
    # 指标的格式化方式，值格式为字符串。支持的格式化选项： 数值格式化： - KMB: 千、百万、十亿格式化，样例：K,Mil,Bil - milli: 处理为毫秒格式，样例：1,000,000 存储格式化： - byte: 处理为字节格式，样例：B/KB...
    data_format: Optional[str] = None
    # 字段的最大值。值可以为空。仅适用于整数和浮点类型。
    max_value: Optional[float] = None
    # 字段的最小值。值可以为空。仅适用于整数和浮点类型。
    min_value: Optional[float] = None
    # 字段的默认值。值可以为空。
    default_value: Optional[Any] = None
    # 用于表示该指标的图标。
    icon: Optional[str] = None
    # 用于表示该指标自身额外的标签。即在 MetricSet 的标签基础上，该指标还具有的额外标签。
    labels: Optional[List[Optional['FieldSpecV1']]] = None
    # 是否为黄金指标。
    golden_metric: Optional[bool] = None
    # 指标的生成方式，如果是 PromMode，该字段为 PromQL语句，能够执行并得到一个可直接使用的 Measure 类型指标。 例如：rate(request_count{}[1m])，在一些场景下结合 aggregator 字段，能够计算出聚合维...
    generator: Optional[str] = None
    # 指标的聚合方式。如果指标本身是聚合的，且聚合方式在多种维度组合下均一致，则不需要配置次字段，其他情况需要配置。一些示例场景如下： 1. Prometheus指标和Metric从时间线维度相同 1.1 rate(cpu_usage_seconds_to...
    aggregator: Optional[str] = None
    # 指标的间隔，值格式为整数或整数数组，单位为微秒。 - 当为单个整数时：表示固定的采集间隔 - 当为整数数组时：表示多个采集间隔，用于支持不同精度的数据采集
    interval_us: Optional[Any] = None
    # 指标的类型。对于无需二次处理的指标，该字段应固定为 gauge。
    type: Optional[str] = None
    # 指标期望的查询模式。值必须是以下之一：range, instant, both。
    query_mode: Optional[str] = None
    # 指标的显示类型。当前未使用。
    display_type: Optional[str] = None
    # 生成该指标时的统计方式，即该指标有多种生成方式。当前仅在基础云监控场景下使用。
    statistics: Optional[List[str]] = None
    # 用于表示该指标的标签。
    tags: Optional[Dict[str, str]] = None
    # 用于表示该指标的附加属性。
    properties: Optional[Dict[str, str]] = None
    # 指标的默认填充策略。 值可以是 null, 0, last, next。
    default_fill_policy: Optional[str] = None

    def get_kind(self) -> str:
        return 'metric'

@dataclass
class ObservationV1(UModelObject):
    """observation class"""
    # 观察名称，在同一个RunbookSet中必须唯一。
    name: Optional[str] = None
    # 观察显示名称。
    display_name: Optional['SemanticStringV1'] = None
    # 观察简短描述。
    short_description: Optional['SemanticStringV1'] = None
    # 观察详细描述信息。
    description: Optional['SemanticStringV1'] = None
    # 现象定义，描述要观察什么以及如何观察。
    phenomenon: Optional['ObservationV1Phenomenon'] = None
    # 结论配置列表，根据现象观察结果进行判断。
    conclusions: Optional[List[Optional['ObservationV1ConclusionsItem']]] = None
    # 观察属性配置。
    properties: Optional[Dict[str, str]] = None
    # 观察标签。
    tags: Optional[Dict[str, str]] = None

    def get_kind(self) -> str:
        return 'observation'

@dataclass
class MetadataV1(UModelObject):
    """metadata class"""
    # 元素在 UModel 系统中的名称。值不能为空。值格式为小写字母数字字符。
    name: Optional[str] = None
    # 元素在 UModel 系统中的显示名称。值不能为空。
    display_name: Optional['SemanticStringV1'] = None
    # 元素在 UModel 系统中的描述。
    description: Optional['SemanticStringV1'] = None
    # 元素在 UModel系统中的简短描述。
    short_description: Optional['SemanticStringV1'] = None
    # 域。值格式为'domain.domain'。可以以点连接。
    domain: Optional[str] = None
    # 元素的发布阶段。默认值为 preview。
    launch_stage: Optional[str] = None
    # 元素在UModel系统中的图标。值格式为'url'。
    icon: Optional[str] = None
    # 用于表示该元素唯一标识。
    uri: Optional[str] = None
    # 用于表示该元素的标签。
    tags: Optional[Dict[str, str]] = None
    # 用于表示该元素的附加属性。
    properties: Optional[Dict[str, str]] = None
    # 背景：在阿里云可观测业务使用中，内置的UModel数据会作为公共UModel（CommonSchema）默认存在，公共UModel数据以引用方式（CommonSchemaRef）配置在UModel，在查询时动态生成UModel实例并附加该字段作为额外...
    common_schema_info: Optional['MetadataV1CommonSchemaInfo'] = None

    def get_kind(self) -> str:
        return 'metadata'

@dataclass
class SchemaV1(UModelObject):
    """schema class"""
    # Schema 的 URL。Core 部分都为 "umodel.aliyun.com"
    url: Optional[str] = None
    # Schema 的版本。命名格式为 "v1.2.3"。
    version: Optional[str] = None

    def get_kind(self) -> str:
        return 'schema'

@dataclass
class TelemetryDataV1(UModelObject):
    """telemetry_data class"""
    # 可观测数据的字段列表。
    fields: Optional[List[Optional['FieldSpecV1']]] = None
    # 可观测数据的时间字段。一般要求时间字段为时间戳类型，支持秒、毫秒、微秒、纳秒。
    time_field: Optional[str] = None
    # 注意：定位和 `name_fields` 有一定重叠，字段已废弃，请使用 `name_fields` 字段第一个值替代。可观测数据的显示字段。即默认展示的字段。
    display_field: Optional[str] = None
    # 可观测数据的显示字段。建议按照显示重要性配置先后顺序，前端、算法等在各类场景会根据特点自由选择，例如极窄/引用场景下只取name_fields的第一个值。 例如：服务操作实体，建议取值为 ["operation_name", "service_nam...
    name_fields: Optional[List[str]] = None
    # 可观测数据的隐藏字段。即不用作展示的字段。
    hidden_fields: Optional[List[str]] = None
    # 可观测数据的标签字段。标签字段默认聚合在一起显示和分析。
    tag_fields: Optional[List[str]] = None
    # 可观测数据的排序字段。即当前数据集的排序字段。
    ordered_fields: Optional[List[str]] = None
    # 可观测数据的默认排序。默认值为 asc。
    default_order: Optional[str] = None

    def get_kind(self) -> str:
        return 'telemetry_data'

@dataclass
class ToolV1(UModelObject):
    """tool class"""
    # 工具名称，在同一个 Toolkit 内必须唯一。
    name: Optional[str] = None
    # 工具显示名称。
    display_name: Optional['SemanticStringV1'] = None
    # 工具简短描述，LLM 用来决定是否调用此工具的关键信息。
    short_description: Optional['SemanticStringV1'] = None
    # 工具详细描述信息。
    description: Optional['SemanticStringV1'] = None
    # 工具输入参数定义，JSON Schema 风格。
    input_schema: Optional['ToolParameterConfigV1'] = None
    # 工具输出参数定义，JSON Schema 风格。
    output_schema: Optional['ToolParameterConfigV1'] = None
    # 操作的风险等级。
    risk_level: Optional[str] = None
    # 操作是否幂等/可重入，重复执行结果一致。
    idempotent: Optional[bool] = None
    # 是否需要确认才能执行操作。
    confirmation_required: Optional[bool] = None
    # 工具级别的额外配置，可覆盖或补充 Toolkit 的 properties。
    properties: Optional[Dict[str, str]] = None
    # 工具标签。
    tags: Optional[Dict[str, str]] = None

    def get_kind(self) -> str:
        return 'tool'
