# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - 主包文件
"""

from __future__ import annotations
import json
import yaml
from typing import Any, Dict, Type, Union, Optional, Tuple, TYPE_CHECKING, get_type_hints, get_origin, get_args
from dataclasses import is_dataclass, fields as dataclass_fields

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelObject, LinkEndpoint, SemanticString
else:
    from .base_types import UModelCoreObject, UModelObject, LinkEndpoint, SemanticString

VERSION = "2.0.0"

# 类型注册表
TYPE_REGISTRY: Dict[str, Type] = {}

# 注册类型的函数
def _register_types():
    """注册所有类型到类型注册表"""
    global TYPE_REGISTRY

    # 注册 aliyun_prometheus 相关类型
    try:
        from . import aliyun_prometheus
        TYPE_REGISTRY["aliyun_prometheus:v1.0.0"] = getattr(aliyun_prometheus, "AliyunPrometheusV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 aliyun_prometheus 导入失败: {e}

    # 注册 data_link 相关类型
    try:
        from . import data_link
        TYPE_REGISTRY["data_link:v1.0.0"] = getattr(data_link, "DataLinkV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 data_link 导入失败: {e}

    # 注册 elasticsearch 相关类型
    try:
        from . import elasticsearch
        TYPE_REGISTRY["elasticsearch:v1.0.0"] = getattr(elasticsearch, "ElasticsearchV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 elasticsearch 导入失败: {e}

    # 注册 entity_set 相关类型
    try:
        from . import entity_set
        TYPE_REGISTRY["entity_set:v1.0.0"] = getattr(entity_set, "EntitySetV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 entity_set 导入失败: {e}

    # 注册 entity_set_link 相关类型
    try:
        from . import entity_set_link
        TYPE_REGISTRY["entity_set_link:v1.0.0"] = getattr(entity_set_link, "EntitySetLinkV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 entity_set_link 导入失败: {e}

    # 注册 entity_source 相关类型
    try:
        from . import entity_source
        TYPE_REGISTRY["entity_source:v1.0.0"] = getattr(entity_source, "EntitySourceV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 entity_source 导入失败: {e}

    # 注册 entity_source_link 相关类型
    try:
        from . import entity_source_link
        TYPE_REGISTRY["entity_source_link:v1.0.0"] = getattr(entity_source_link, "EntitySourceLinkV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 entity_source_link 导入失败: {e}

    # 注册 event_set 相关类型
    try:
        from . import event_set
        TYPE_REGISTRY["event_set:v1.0.0"] = getattr(event_set, "EventSetV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 event_set 导入失败: {e}

    # 注册 explorer 相关类型
    try:
        from . import explorer
        TYPE_REGISTRY["explorer:v1.0.0"] = getattr(explorer, "ExplorerV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 explorer 导入失败: {e}

    # 注册 explorer_link 相关类型
    try:
        from . import explorer_link
        TYPE_REGISTRY["explorer_link:v1.0.0"] = getattr(explorer_link, "ExplorerLinkV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 explorer_link 导入失败: {e}

    # 注册 external_storage 相关类型
    try:
        from . import external_storage
        TYPE_REGISTRY["external_storage:v1.0.0"] = getattr(external_storage, "ExternalStorageV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 external_storage 导入失败: {e}

    # 注册 log_set 相关类型
    try:
        from . import log_set
        TYPE_REGISTRY["log_set:v1.0.0"] = getattr(log_set, "LogSetV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 log_set 导入失败: {e}

    # 注册 metric_set 相关类型
    try:
        from . import metric_set
        TYPE_REGISTRY["metric_set:v1.0.0"] = getattr(metric_set, "MetricSetV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 metric_set 导入失败: {e}

    # 注册 mysql 相关类型
    try:
        from . import mysql
        TYPE_REGISTRY["mysql:v1.0.0"] = getattr(mysql, "MysqlV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 mysql 导入失败: {e}

    # 注册 profile_set 相关类型
    try:
        from . import profile_set
        TYPE_REGISTRY["profile_set:v1.0.0"] = getattr(profile_set, "ProfileSetV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 profile_set 导入失败: {e}

    # 注册 prometheus 相关类型
    try:
        from . import prometheus
        TYPE_REGISTRY["prometheus:v1.0.0"] = getattr(prometheus, "PrometheusV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 prometheus 导入失败: {e}

    # 注册 runbook_link 相关类型
    try:
        from . import runbook_link
        TYPE_REGISTRY["runbook_link:v1.0.0"] = getattr(runbook_link, "RunbookLinkV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 runbook_link 导入失败: {e}

    # 注册 runbook_set 相关类型
    try:
        from . import runbook_set
        TYPE_REGISTRY["runbook_set:v1.0.0"] = getattr(runbook_set, "RunbookSetV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 runbook_set 导入失败: {e}

    # 注册 sls_entitystore 相关类型
    try:
        from . import sls_entitystore
        TYPE_REGISTRY["sls_entitystore:v1.0.0"] = getattr(sls_entitystore, "SlsEntitystoreV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 sls_entitystore 导入失败: {e}

    # 注册 sls_logstore 相关类型
    try:
        from . import sls_logstore
        TYPE_REGISTRY["sls_logstore:v1.0.0"] = getattr(sls_logstore, "SlsLogstoreV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 sls_logstore 导入失败: {e}

    # 注册 sls_metricstore 相关类型
    try:
        from . import sls_metricstore
        TYPE_REGISTRY["sls_metricstore:v1.0.0"] = getattr(sls_metricstore, "SlsMetricstoreV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 sls_metricstore 导入失败: {e}

    # 注册 storage_link 相关类型
    try:
        from . import storage_link
        TYPE_REGISTRY["storage_link:v1.0.0"] = getattr(storage_link, "StorageLinkV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 storage_link 导入失败: {e}

    # 注册 trace_set 相关类型
    try:
        from . import trace_set
        TYPE_REGISTRY["trace_set:v1.0.0"] = getattr(trace_set, "TraceSetV100", None)
    except (ImportError, AttributeError) as e:
        pass  # 模块 trace_set 导入失败: {e}


# 延迟注册所有类型，避免循环导入
def register_all_types():
    """手动注册所有类型（用于解决循环导入问题）"""
    _register_types()

# 尝试自动注册
try:
    _register_types()
except Exception:
    pass  # 如果自动注册失败，可以手动调用register_all_types()

# 解析函数
def parse_json(data: bytes, target_type: Type) -> Any:
    """从JSON数据解析对象"""
    json_data = json.loads(data)
    try:
        return target_type(**json_data)
    except TypeError as e:
        # 如果直接实例化失败，尝试简单赋值
        instance = target_type()
        for key, value in json_data.items():
            if hasattr(instance, key):
                setattr(instance, key, value)
        return instance

def parse_yaml(data: bytes, target_type: Type) -> Any:
    """从YAML数据解析对象"""
    yaml_data = yaml.safe_load(data)
    try:
        return target_type(**yaml_data)
    except TypeError as e:
        # 如果直接实例化失败，尝试简单赋值
        instance = target_type()
        for key, value in yaml_data.items():
            if hasattr(instance, key):
                setattr(instance, key, value)
        return instance

def _convert_value_to_type(value: Any, target_type: Type) -> Any:
    """递归地将值转换为目标类型
    
    Args:
        value: 要转换的值（通常是从 YAML/JSON 解析的 dict/list）
        target_type: 目标类型（可能是 dataclass、Optional、List 等）
    
    Returns:
        转换后的值
    """
    # 如果值是 None，直接返回
    if value is None:
        return None
    
    # 获取类型的 origin（如 List, Optional）和 args（如 List[str] 中的 str）
    origin = get_origin(target_type)
    args = get_args(target_type)
    
    # 处理 Optional[X] 类型（实际上是 Union[X, None]）
    if origin is Union:
        # 找到非 None 的类型
        non_none_types = [arg for arg in args if arg is not type(None)]
        if non_none_types:
            # 递归处理第一个非 None 类型
            return _convert_value_to_type(value, non_none_types[0])
        return value
    
    # 处理 List 类型
    if origin is list:
        if not isinstance(value, list):
            return value
        if args:
            # 递归转换列表中的每个元素
            element_type = args[0]
            return [_convert_value_to_type(item, element_type) for item in value]
        return value
    
    # 处理 Dict 类型
    if origin is dict:
        return value
    
    # 处理 dataclass 类型
    if is_dataclass(target_type) and isinstance(value, dict):
        # 递归转换嵌套的 dataclass
        return _dict_to_dataclass(target_type, value)
    
    # 其他情况直接返回
    return value


def _dict_to_dataclass(dataclass_type: Type, data: Dict[str, Any]) -> Any:
    """将字典递归转换为 dataclass 实例
    
    Args:
        dataclass_type: 目标 dataclass 类型
        data: 字典数据
    
    Returns:
        dataclass 实例
    """
    if not is_dataclass(dataclass_type):
        return data
    
    try:
        # 获取 dataclass 的类型提示
        type_hints = get_type_hints(dataclass_type)
    except Exception:
        # 如果获取类型提示失败，使用字段定义
        type_hints = {}
        for field in dataclass_fields(dataclass_type):
            type_hints[field.name] = field.type
    
    # 转换每个字段的值
    converted_data = {}
    for key, value in data.items():
        if key in type_hints:
            # 递归转换嵌套的类型
            converted_data[key] = _convert_value_to_type(value, type_hints[key])
        else:
            # 没有类型提示的字段保持原样
            converted_data[key] = value
    
    # 创建 dataclass 实例
    try:
        return dataclass_type(**converted_data)
    except Exception:
        # 如果构造失败，尝试无参构造后赋值
        instance = dataclass_type()
        for key, value in converted_data.items():
            if hasattr(instance, key):
                setattr(instance, key, value)
        return instance


def _create_instance_from_data(target_type: Type, data: Dict[str, Any]) -> Any:
    """从数据创建类型实例的辅助函数"""
    # 首先尝试使用递归转换
    if is_dataclass(target_type):
        try:
            return _dict_to_dataclass(target_type, data)
        except Exception as e:
            # 如果递归转换失败，继续尝试旧的方法
            pass
    
    try:
        # 尝试直接使用构造函数
        return target_type(**data)
    except Exception:
        try:
            # 尝试无参构造后赋值
            instance = target_type()
            for key, value in data.items():
                if hasattr(instance, key):
                    # 处理特殊类型
                    if key == 'metadata' and isinstance(value, dict):
                        # 尝试转换为SemanticString
                        if 'description' in value and isinstance(value['description'], dict):
                            value['description'] = SemanticString.from_dict(value['description'])
                    setattr(instance, key, value)
            return instance
        except Exception as e:
            # 如果都失败了，返回一个简单的对象
            class SimpleObject:
                def __init__(self):
                    for key, value in data.items():
                        setattr(self, key, value)
                def get_kind(self):
                    return data.get('kind', 'unknown')
                def validate(self):
                    return None
                def get_schema(self):
                    return getattr(self, 'schema', None)
                def get_metadata(self):
                    return getattr(self, 'metadata', None)
            return SimpleObject()

def parse_umodel_json(data: bytes) -> UModelCoreObject:
    """自动检测类型并解析JSON"""
    # 先解析header获取kind和version
    json_data = json.loads(data)
    
    kind = json_data.get('kind')
    if not kind:
        raise ValueError('missing required field: kind')
    
    metadata = json_data.get('metadata')
    if not metadata:
        raise ValueError('missing required field: metadata')
    
    domain = metadata.get('domain') if isinstance(metadata, dict) else None
    if not domain:
        raise ValueError('missing required field: metadata.domain')
    
    name = metadata.get('name') if isinstance(metadata, dict) else None
    if not name:
        raise ValueError('missing required field: metadata.name')
    
    schema_info = json_data.get('schema', {})
    version = schema_info.get('version')
    if not version:
        raise ValueError('missing required field: schema.version')
    
    spec = json_data.get('spec')
    if spec is None:
        raise ValueError('missing required field: spec')
    
    if isinstance(spec, dict) and len(spec) == 0:
        raise ValueError('spec field cannot be empty')
    
    # 构建类型键
    type_key = f'{kind}:{version}'
    
    # 查找类型
    target_type = TYPE_REGISTRY.get(type_key)
    if not target_type:
        # 尝试兼容版本
        if version.startswith('v0.'):
            alt_type_key = f'{kind}:v1.0.0'
            target_type = TYPE_REGISTRY.get(alt_type_key)
        if not target_type:
            raise ValueError(f'unknown type: {type_key}')
    
    # 创建实例
    return _create_instance_from_data(target_type, json_data)

def parse_umodel_yaml(data: bytes) -> UModelCoreObject:
    """自动检测类型并解析YAML"""
    # 先解析header获取kind和version
    yaml_data = yaml.safe_load(data)
    
    kind = yaml_data.get('kind')
    if not kind:
        raise ValueError('missing required field: kind')
    
    metadata = yaml_data.get('metadata')
    if not metadata:
        raise ValueError('missing required field: metadata')
    
    domain = metadata.get('domain') if isinstance(metadata, dict) else None
    if not domain:
        raise ValueError('missing required field: metadata.domain')
    
    name = metadata.get('name') if isinstance(metadata, dict) else None
    if not name:
        raise ValueError('missing required field: metadata.name')
    
    schema_info = yaml_data.get('schema', {})
    version = schema_info.get('version')
    if not version:
        raise ValueError('missing required field: schema.version')
    
    spec = yaml_data.get('spec')
    if spec is None:
        raise ValueError('missing required field: spec')
    
    if isinstance(spec, dict) and len(spec) == 0:
        raise ValueError('spec field cannot be empty')
    
    # 构建类型键
    type_key = f'{kind}:{version}'
    
    # 查找类型
    target_type = TYPE_REGISTRY.get(type_key)
    if not target_type:
        # 尝试兼容版本
        if version.startswith('v0.'):
            alt_type_key = f'{kind}:v1.0.0'
            target_type = TYPE_REGISTRY.get(alt_type_key)
        if not target_type:
            raise ValueError(f'unknown type: {type_key}')
    
    # 创建实例
    return _create_instance_from_data(target_type, yaml_data)

# 导入UModelLinkObject用于类型检查
try:
    from .base_types import UModelLinkObject
except ImportError:
    UModelLinkObject = None

# 工具函数
def is_core_object(obj: Any) -> bool:
    """判断对象是否实现了UModelCoreObject接口"""
    return isinstance(obj, UModelCoreObject)

def is_link_object(obj: Any) -> bool:
    """判断对象是否实现了UModelLinkObject接口"""
    if UModelLinkObject is None:
        return False
    return isinstance(obj, UModelLinkObject)

def get_object_metadata(obj: Any) -> Optional[Any]:
    """获取任意UModel对象的Metadata（如果支持）"""
    if is_core_object(obj):
        return obj.get_metadata()
    return None

def get_object_schema(obj: Any) -> Optional[Any]:
    """获取任意UModel对象的Schema（如果支持）"""
    if is_core_object(obj):
        return obj.get_schema()
    return None

def get_link_endpoints(obj: Any) -> Tuple[Optional[LinkEndpoint], Optional[LinkEndpoint]]:
    """获取Link对象的源和目标端点（如果支持）"""
    if is_link_object(obj):
        return obj.get_src(), obj.get_dest()
    return None, None
