# Code generated by schema_python_generator_v2.py. DO NOT EDIT.

"""
UModel Python SDK - victoriametrics Schema
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint
else:
    from .base_types import UModelCoreObject, UModelLinkObject, SemanticString, LinkEndpoint

# 延迟导入共享类型以避免循环依赖
try:
    from .shared_types import *
except ImportError:
    pass

@dataclass
class VictoriametricsV100(UModelCoreObject):
    """victoriametrics class"""
    kind: Optional[str] = None
    schema: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None
    # VictoriaMetrics 的核心配置部分。UModel 只使用这些字段生成 PromQL 查询计划，不直接执行查询，也不保存明文凭据。
    spec: Optional['VictoriametricsV100Spec'] = None

    def get_kind(self) -> str:
        return 'victoriametrics'

    def get_schema(self) -> Optional[Any]:
        return getattr(self, 'schema', None)

    def get_metadata(self) -> Optional[Any]:
        return getattr(self, 'metadata', None)

@dataclass
class VictoriametricsV100Spec:
    """VictoriaMetrics 的核心配置部分。UModel 只使用这些字段生成 PromQL 查询计划，不直接执行查询，也不保存明文凭据。"""
    # 该存储渲染所用的查询家族。VictoriaMetrics 兼容 PromQL，设为 label-timeseries 即可复用 Prometheus 查询计划渲染器，无需编写任何 Go 代码——这正是“新增同族后端只写配置”的体现；不设则该存储仅透传...
    family: Optional[str] = None
    # VictoriaMetrics 或 PromQL 兼容服务的访问地址，例如 http://victoriametrics:8428。
    endpoint: Optional[str] = None
    # PromQL HTTP API 前缀。默认值为 /api/v1。
    api_prefix: Optional[str] = None
    # 默认 PromQL 查询类型。instant 表示即时查询，range 表示区间查询。
    default_query_type: Optional[str] = None
    # 区间查询的默认 step，例如 60s、1m。
    default_step: Optional[str] = None
    # PromQL 查询规划使用的默认回看窗口，例如 5m。
    lookback_delta: Optional[str] = None
    # 可选租户标识，用于多租户 VictoriaMetrics 集群版。
    tenant: Optional[str] = None
    # 多租户系统使用的租户 HTTP 头名称，例如 X-Scope-OrgID。
    tenant_header: Optional[str] = None
    # 凭据引用标识，例如 secret://victoriametrics-prod-readonly。不得在 UModel 中保存明文用户名、密码或 Token。
    credential_ref: Optional[str] = None
    # 是否校验 TLS 证书。默认值为 true。
    tls_verify: Optional[bool] = None
    # 外部标签，用于 query planning 时补充查询上下文或结果来源说明。
    external_labels: Optional[Dict[str, str]] = None
    # 非敏感 HTTP 头，用于租户、路由等查询上下文。不得存放认证密钥。
    headers: Optional[Dict[str, str]] = None
    # VictoriaMetrics 的额外非敏感配置，以键值对形式存储。
    properties: Optional[Dict[str, str]] = None
    # 用于标注该 VictoriaMetrics 存储的标签。
    tags: Optional[Dict[str, str]] = None
