kind: entity_set_link
schema:
  url: "umodel.aliyun.com"
  version: "v0.1.0"
metadata:
  name: "k8s.cluster_contains_k8s.namespace"
  domain: k8s
  display_name:
    en_us: "Cluster Contains Namespace"
    zh_cn: "集群包含命名空间"
  description:
    en_us: "A cluster contains namespaces."
    zh_cn: "集群包含命名空间。"
spec:
  src:
    domain: k8s
    kind: entity_set
    name: k8s.cluster
  dest:
    domain: k8s
    kind: entity_set
    name: k8s.namespace
  entity_link_type: contains
