kind: data_link
schema:
  url: "umodel.aliyun.com"
  version: "v1.0.0"
metadata:
  name: "devops.service_related_to_devops.log.service"
  domain: devops
  display_name:
    en_us: "Service related to service logs"
    zh_cn: "服务关联服务日志"
spec:
  src:
    domain: devops
    kind: entity_set
    name: devops.service
  dest:
    domain: devops
    kind: log_set
    name: devops.log.service
  fields_mapping:
    id: service_id
    environment: environment
  data_link_type: related_to
