kind: entity_set_link
schema:
  url: "umodel.aliyun.com"
  version: "v0.1.0"
metadata:
  name: "devops.deployment_targets_k8s.workload"
  domain: devops
  display_name:
    en_us: "Deployment Targets Workload"
    zh_cn: "部署指向工作负载"
  description:
    en_us: "A DevOps deployment targets a Kubernetes workload."
    zh_cn: "DevOps 部署指向 Kubernetes 工作负载。"
spec:
  src:
    domain: devops
    kind: entity_set
    name: devops.deployment
  dest:
    domain: k8s
    kind: entity_set
    name: k8s.workload
  entity_link_type: targets
