// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// ClickhouseV100 represents clickhouse
type ClickhouseV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec ClickHouse 的核心配置部分。UModel 只使用这些字段生成 SQL 查询计划，不直接执行查询，也不保存明文凭据。
	Spec *ClickhouseV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证ClickhouseV100是否符合schema定义
func (s *ClickhouseV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ClickhouseV100的类型标识
func (s *ClickhouseV100) GetKind() string {
	return "clickhouse"
}

// GetSchema 获取ClickhouseV100的Schema信息
func (s *ClickhouseV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取ClickhouseV100的Metadata信息
func (s *ClickhouseV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// ClickhouseV100Spec ClickHouse 的核心配置部分。UModel 只使用这些字段生成 SQL 查询计划，不直接执行查询，也不保存明文凭据。
type ClickhouseV100Spec struct {
	// Family 该存储渲染所用的查询家族。设为 sql-table 即可经由 sql-table 渲染器把 get_metrics 渲染为 SQL；不设则该存储仅透传、不渲染。该家族此后的每个后端都只是配置。
	Family string `json:"family,omitempty" yaml:"family,omitempty"`
	// Endpoint ClickHouse 的访问地址，例如 http://clickhouse:8123。
	Endpoint string `json:"endpoint" yaml:"endpoint"`
	// Database 查询所用的数据库名。
	Database string `json:"database,omitempty" yaml:"database,omitempty"`
	// Table 指标所在的表名。sql-table 渲染器从该表 SELECT 数据。
	Table string `json:"table" yaml:"table"`
	// TimeColumn 时间列名，用于时间范围过滤与降采样。默认值为 timestamp。
	TimeColumn string `json:"time_column,omitempty" yaml:"time_column,omitempty"`
	// ValueColumn 指标数值列名。默认值为 value。
	ValueColumn string `json:"value_column,omitempty" yaml:"value_column,omitempty"`
	// MetricColumn 指标名所在的列名，用于按指标过滤。默认值为 metric_name。
	MetricColumn string `json:"metric_column,omitempty" yaml:"metric_column,omitempty"`
	// DefaultQueryType 默认查询类型。instant 表示取最新值，range 表示区间降采样。
	DefaultQueryType string `json:"default_query_type,omitempty" yaml:"default_query_type,omitempty"`
	// DefaultStep 区间查询的默认降采样步长，例如 60s、1m。
	DefaultStep string `json:"default_step,omitempty" yaml:"default_step,omitempty"`
	// CredentialRef 凭据引用标识，例如 secret://clickhouse-prod-readonly。不得在 UModel 中保存明文用户名、密码或 Token。
	CredentialRef string `json:"credential_ref,omitempty" yaml:"credential_ref,omitempty"`
	// TlsVerify 是否校验 TLS 证书。默认值为 true。
	TlsVerify bool `json:"tls_verify,omitempty" yaml:"tls_verify,omitempty"`
	// Properties ClickHouse 的额外非敏感配置，以键值对形式存储。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Tags 用于标注该 ClickHouse 存储的标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// Validate 验证ClickhouseV100Spec是否符合schema定义
func (s *ClickhouseV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
