// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// ElasticsearchV100 represents elasticsearch
type ElasticsearchV100 struct {
	Kind     string      `json:"kind" yaml:"kind"`
	Schema   *SchemaV1   `json:"schema" yaml:"schema"`
	Metadata *MetadataV1 `json:"metadata" yaml:"metadata"`
	// Spec Elasticsearch 的核心配置部分。UModel 只使用这些字段生成 Elasticsearch 查询计划，不直接执行查询，也不保存明文凭据。
	Spec *ElasticsearchV100Spec `json:"spec" yaml:"spec"`
}

// Validate 验证ElasticsearchV100是否符合schema定义
func (s *ElasticsearchV100) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ElasticsearchV100的类型标识
func (s *ElasticsearchV100) GetKind() string {
	return "elasticsearch"
}

// GetSchema 获取ElasticsearchV100的Schema信息
func (s *ElasticsearchV100) GetSchema() *SchemaV1 {
	if s == nil {
		return nil
	}
	return s.Schema
}

// GetMetadata 获取ElasticsearchV100的Metadata信息
func (s *ElasticsearchV100) GetMetadata() *MetadataV1 {
	if s == nil {
		return nil
	}
	return s.Metadata
}

// ElasticsearchV100Spec Elasticsearch 的核心配置部分。UModel 只使用这些字段生成 Elasticsearch 查询计划，不直接执行查询，也不保存明文凭据。
type ElasticsearchV100Spec struct {
	// Endpoint Elasticsearch 集群访问地址，例如 https://es.example.com:9200。
	Endpoint string `json:"endpoint" yaml:"endpoint"`
	// Index 默认查询索引名称，也可以是 Elasticsearch 支持的索引通配表达式。
	Index string `json:"index" yaml:"index"`
	// IndexPattern 面向按时间滚动索引的索引模式，例如 logs-${yyyy.MM.dd}。如果为空，查询规划使用 index 字段。
	IndexPattern string `json:"index_pattern,omitempty" yaml:"index_pattern,omitempty"`
	// Version Elasticsearch 版本号或版本族，例如 7.x、8.x。
	Version string `json:"version,omitempty" yaml:"version,omitempty"`
	// QueryDialect 查询生成方言。默认生成 Elasticsearch Query DSL。
	QueryDialect string `json:"query_dialect,omitempty" yaml:"query_dialect,omitempty"`
	// TimeField 时间过滤字段名，用于将请求时间范围下推到 Elasticsearch 查询中。
	TimeField string `json:"time_field,omitempty" yaml:"time_field,omitempty"`
	// DefaultSize 未显式指定 limit 时生成查询的默认 size。
	DefaultSize int64 `json:"default_size,omitempty" yaml:"default_size,omitempty"`
	// MaxSize 查询规划允许生成的最大 size，用于避免生成过大的查询计划。
	MaxSize int64 `json:"max_size,omitempty" yaml:"max_size,omitempty"`
	// Routing 可选的 Elasticsearch routing 值。用于规划需要固定 routing 的查询。
	Routing string `json:"routing,omitempty" yaml:"routing,omitempty"`
	// CredentialRef 凭据引用标识，例如 secret://es-prod-readonly。不得在 UModel 中保存明文用户名、密码或 Token。
	CredentialRef string `json:"credential_ref,omitempty" yaml:"credential_ref,omitempty"`
	// TlsVerify 是否校验 TLS 证书。默认值为 true。
	TlsVerify bool `json:"tls_verify,omitempty" yaml:"tls_verify,omitempty"`
	// Headers 非敏感 HTTP 头，用于租户、路由等查询上下文。不得存放认证密钥。
	Headers map[string]string `json:"headers,omitempty" yaml:"headers,omitempty"`
	// Properties Elasticsearch 的额外非敏感配置，以键值对形式存储。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Tags 用于标注该 Elasticsearch 存储的标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// Validate 验证ElasticsearchV100Spec是否符合schema定义
func (s *ElasticsearchV100Spec) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
