// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

package umodel

import (
	"encoding/json"
	"time"
)

// SemanticStringV1 支持多语言的语义字符串类型，可以是简单字符串或多语言对象
type SemanticStringV1 struct {
	// ZhCn 中文描述
	ZhCn string `json:"zh_cn,omitempty" yaml:"zh_cn,omitempty"`
	// EnUs 英文描述
	EnUs string `json:"en_us,omitempty" yaml:"en_us,omitempty"`
}

// Validate 验证SemanticStringV1是否符合schema定义
func (s *SemanticStringV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取SemanticStringV1的类型标识
func (s *SemanticStringV1) GetKind() string {
	return "semantic_string"
}

// ConstraintTypeV1 约束条件属性定义
type ConstraintTypeV1 struct {
	// Required 是否为必填字段
	Required bool `json:"required,omitempty" yaml:"required,omitempty"`
	// DefaultValue 默认值，需要和 type 类型匹配。
	DefaultValue interface{} `json:"default_value,omitempty" yaml:"default_value,omitempty"`
	// Pattern 正则表达式模式
	Pattern string `json:"pattern,omitempty" yaml:"pattern,omitempty"`
	// MinLen 最小长度
	MinLen float64 `json:"min_len,omitempty" yaml:"min_len,omitempty"`
	// MaxLen 最大长度
	MaxLen float64 `json:"max_len,omitempty" yaml:"max_len,omitempty"`
	// Enum 枚举值列表
	Enum *ConstraintTypeV1Enum `json:"enum,omitempty" yaml:"enum,omitempty"`
	// Array 数组约束定义，内部的 item 可以嵌套定义 metadata_properties，也支持特殊引用规则 "type_ref"。
	Array *ConstraintTypeV1Array `json:"array,omitempty" yaml:"array,omitempty"`
	// Map Map约束定义，内部的 key 和 value 可以嵌套定义 metadata_properties，也支持特殊引用规则 "type_ref"。
	Map map[string]interface{} `json:"map,omitempty" yaml:"map,omitempty"`
	// Oneof 多类型约束定义，即该字段可以有多种类型，例如支持 number 和 array[number]。其中每个元素为一个单独的类型定义。
	Oneof []interface{} `json:"oneOf,omitempty" yaml:"oneOf,omitempty"`
	// Advanced 高级约束定义，用于支持更复杂的约束条件，包括逻辑操作和字段引用。 主要功能： 1. 支持逻辑操作符：and, or, not, eq, ne, gt, ge, lt, le, in, nin, exists, regex 2. 支持字段路径引用： -...
	Advanced *ConstraintTypeV1Advanced `json:"advanced,omitempty" yaml:"advanced,omitempty"`
}

// Validate 验证ConstraintTypeV1是否符合schema定义
func (s *ConstraintTypeV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ConstraintTypeV1的类型标识
func (s *ConstraintTypeV1) GetKind() string {
	return "constraint_type"
}

// AutomationConfigV1 represents automation_config
type AutomationConfigV1 struct {
	// Name 自动化项名称，在同一个RunbookSet中必须唯一。
	Name string `json:"name" yaml:"name"`
	// DisplayName 自动化项显示名称。
	DisplayName *SemanticStringV1 `json:"display_name" yaml:"display_name"`
	// ShortDescription 自动化项简短描述。
	ShortDescription *SemanticStringV1 `json:"short_description" yaml:"short_description"`
	// Description 自动化项详细描述信息。
	Description *SemanticStringV1 `json:"description,omitempty" yaml:"description,omitempty"`
	// AutomationType 自动化类型，如action、script、webhook等。
	AutomationType string `json:"automation_type" yaml:"automation_type"`
	// Trigger 触发条件配置。
	Trigger *AutomationConfigV1Trigger `json:"trigger" yaml:"trigger"`
	// Properties 自动化项属性配置。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Tags 自动化项标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// Validate 验证AutomationConfigV1是否符合schema定义
func (s *AutomationConfigV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取AutomationConfigV1的类型标识
func (s *AutomationConfigV1) GetKind() string {
	return "automation_config"
}

// SkillConfigV1 represents skill_config
type SkillConfigV1 struct {
	// Name 技能名称（唯一标识），仅支持小写字母、数字和连字符，不能以连字符开头或结尾，不能包含连续连字符。
	Name string `json:"name" yaml:"name"`
	// DisplayName 技能显示名称。
	DisplayName *SemanticStringV1 `json:"display_name" yaml:"display_name"`
	// Description 技能描述，说明技能的功能和使用场景，帮助 Agent 识别何时使用该技能。
	Description *SemanticStringV1 `json:"description" yaml:"description"`
	// License 技能的许可证信息。
	License string `json:"license,omitempty" yaml:"license,omitempty"`
	// Compatibility 技能的环境兼容性要求，如依赖的系统包、网络访问需求等。
	Compatibility string `json:"compatibility,omitempty" yaml:"compatibility,omitempty"`
	// AllowedTools 预授权工具列表，空格分隔的工具标识符。
	AllowedTools string `json:"allowed_tools,omitempty" yaml:"allowed_tools,omitempty"`
	// Metadata 技能的额外元数据，如作者、版本等。
	Metadata map[string]string `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	// Tags 技能标签，用于分类和检索。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
	// Files 技能文件列表，包含 SKILL.md 及其他辅助文件（如 scripts/、references/、assets/ 下的文件）。
	Files []*SkillConfigV1FilesItem `json:"files,omitempty" yaml:"files,omitempty"`
	// SkillUrl 技能包的外部URL地址（如OSS地址），与files字段二选一。当使用URL时，技能文件从该地址加载。
	SkillUrl string `json:"skill_url,omitempty" yaml:"skill_url,omitempty"`
	// Priority 技能优先级，用于排序和选择。值越小优先级越高。
	Priority int64 `json:"priority,omitempty" yaml:"priority,omitempty"`
	// LastUpdated 最后更新时间。
	LastUpdated time.Time `json:"last_updated,omitempty" yaml:"last_updated,omitempty"`
}

// Validate 验证SkillConfigV1是否符合schema定义
func (s *SkillConfigV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取SkillConfigV1的类型标识
func (s *SkillConfigV1) GetKind() string {
	return "skill_config"
}

// ToolkitV1 represents toolkit
type ToolkitV1 struct {
	// Name 工具箱名称，在同一个 RunbookSet 内必须唯一。
	Name string `json:"name" yaml:"name"`
	// DisplayName 工具箱显示名称。
	DisplayName *SemanticStringV1 `json:"display_name" yaml:"display_name"`
	// ShortDescription 工具箱简短描述。
	ShortDescription *SemanticStringV1 `json:"short_description,omitempty" yaml:"short_description,omitempty"`
	// Description 工具箱详细描述信息。
	Description *SemanticStringV1 `json:"description,omitempty" yaml:"description,omitempty"`
	// ToolkitType 工具箱类型，如 mcp、pop_api、api_call、script、webhook 等。
	ToolkitType string `json:"toolkit_type" yaml:"toolkit_type"`
	// Configs 运行时配置，如连接信息、认证、超时等，Toolkit 内所有 Tool 继承使用。
	Configs map[string]interface{} `json:"configs,omitempty" yaml:"configs,omitempty"`
	// Properties 扩展元数据，描述性属性，自由扩展的 k-v。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Tags 共享标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
	// Tools 工具列表。
	Tools []*ToolV1 `json:"tools" yaml:"tools"`
}

// Validate 验证ToolkitV1是否符合schema定义
func (s *ToolkitV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ToolkitV1的类型标识
func (s *ToolkitV1) GetKind() string {
	return "toolkit"
}

// FieldSpecV1 represents field_spec
type FieldSpecV1 struct {
	// Name Field 在 UModel 系统中的名称。值不能为空。值格式为小写字母数字字符。
	Name string `json:"name" yaml:"name"`
	// DisplayName Field 在 UModel 系统中的显示名称。值不能为空。
	DisplayName *SemanticStringV1 `json:"display_name,omitempty" yaml:"display_name,omitempty"`
	// Description Field 在 UModel 系统中的描述。
	Description *SemanticStringV1 `json:"description,omitempty" yaml:"description,omitempty"`
	// ShortDescription Field 在 UModel 系统中的简短描述。
	ShortDescription *SemanticStringV1 `json:"short_description,omitempty" yaml:"short_description,omitempty"`
	// LaunchStage 元素的发布阶段。默认值为 preview。
	LaunchStage string `json:"launch_stage,omitempty" yaml:"launch_stage,omitempty"`
	// Type 字段的类型。值必须是以下之一：string、integer、float、boolean、time、json_object、json_array。值不能为空。
	Type string `json:"type" yaml:"type"`
	// ValueMapping 对于枚举值的映射和解释，为了更好的展示映射值含义，对于 mapping 的 value 字段单独定义，value 包含4个字段："name"、"display_name"、"description"和"short_description"。例如，"s...
	ValueMapping map[string]*ValueMappingV1 `json:"value_mapping,omitempty" yaml:"value_mapping,omitempty"`
	// Unit 指标的单位，值格式为字符串。 注意：单位仅用于展示，不会进行格式转换，例如 ms 不会自动根据大小转换为 s。 最佳实践：首先配置 data_format ，在大部分可观测场景下，data_format 即可满足需求，unit 填写为空即可。 若不满...
	Unit string `json:"unit,omitempty" yaml:"unit,omitempty"`
	// DataFormat 指标的格式化方式，值格式为字符串。支持的格式化选项： 数值格式化： - KMB: 千、百万、十亿格式化，样例：K,Mil,Bil - milli: 处理为毫秒格式，样例：1,000,000 存储格式化： - byte: 处理为字节格式，样例：B/KB...
	DataFormat string `json:"data_format,omitempty" yaml:"data_format,omitempty"`
	// Analysable 用于表示字段是否可分析，即作为Group By的列。默认值为false。
	Analysable bool `json:"analysable,omitempty" yaml:"analysable,omitempty"`
	// Filterable 用于表示字段是否可过滤，即支持索引过滤。默认值为false。
	Filterable bool `json:"filterable,omitempty" yaml:"filterable,omitempty"`
	// Orderable 用于表示字段是否可排序。默认值为false。
	Orderable bool `json:"orderable,omitempty" yaml:"orderable,omitempty"`
	// DefaultOrder 用于表示字段的默认排序顺序。值必须是以下之一：asc、desc。默认值为asc。
	DefaultOrder string `json:"default_order,omitempty" yaml:"default_order,omitempty"`
	// Pattern 正则表达式，用于定义字段的值范围（字符串）。
	Pattern string `json:"pattern,omitempty" yaml:"pattern,omitempty"`
	// MaxLength 字符串值的最大长度。仅适用于字符串类型。
	MaxLength int64 `json:"max_length,omitempty" yaml:"max_length,omitempty"`
	// Example 字段值的示例。值可以为空。
	Example interface{} `json:"example,omitempty" yaml:"example,omitempty"`
	// MaxValue 字段的最大值。值可以为空。仅适用于整数和浮点类型。
	MaxValue float64 `json:"max_value,omitempty" yaml:"max_value,omitempty"`
	// MinValue 字段的最小值。值可以为空。仅适用于整数和浮点类型。
	MinValue float64 `json:"min_value,omitempty" yaml:"min_value,omitempty"`
	// DefaultValue 字段的默认值。值可以为空。
	DefaultValue interface{} `json:"default_value,omitempty" yaml:"default_value,omitempty"`
	// Icon Field 在 UModel 系统中的图标。值格式为'url'。
	Icon string `json:"icon,omitempty" yaml:"icon,omitempty"`
	// Uri 用于表示该字段唯一标识。
	Uri string `json:"uri,omitempty" yaml:"uri,omitempty"`
	// Tags 用于表示该 Field 的标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
	// Properties 用于表示该 Field 的附加属性。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
}

// Validate 验证FieldSpecV1是否符合schema定义
func (s *FieldSpecV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取FieldSpecV1的类型标识
func (s *FieldSpecV1) GetKind() string {
	return "field_spec"
}

// LinkV1 represents link
type LinkV1 struct {
	// Src 源 Set 的标识。值不能为空。
	Src *LinkV1Src `json:"src,omitempty" yaml:"src,omitempty"`
	// Dest 目标 Set 的标识。值不能为空。
	Dest *LinkV1Dest `json:"dest,omitempty" yaml:"dest,omitempty"`
	// FilterByEntity 在部分Entity具备的Link中，用于标识这部分Entity的过滤条件。
	FilterByEntity string `json:"filter_by_entity,omitempty" yaml:"filter_by_entity,omitempty"`
	// Priority Link 的优先级。值可以为空。默认值为5。
	Priority int64 `json:"priority,omitempty" yaml:"priority,omitempty"`
}

// Validate 验证LinkV1是否符合schema定义
func (s *LinkV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取LinkV1的类型标识
func (s *LinkV1) GetKind() string {
	return "link"
}

// ValueMappingV1 represents value_mapping
type ValueMappingV1 struct {
	// Name 在 UModel 系统中的名称。值不能为空。值格式为小写字母数字字符。
	Name string `json:"name" yaml:"name"`
	// DisplayName 在 UModel 系统中的显示名称。值不能为空。
	DisplayName *SemanticStringV1 `json:"display_name,omitempty" yaml:"display_name,omitempty"`
	// Description 在 UModel 系统中的描述。
	Description *SemanticStringV1 `json:"description,omitempty" yaml:"description,omitempty"`
	// ShortDescription 在 UModel 系统中的简短描述。
	ShortDescription *SemanticStringV1 `json:"short_description,omitempty" yaml:"short_description,omitempty"`
}

// Validate 验证ValueMappingV1是否符合schema定义
func (s *ValueMappingV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ValueMappingV1的类型标识
func (s *ValueMappingV1) GetKind() string {
	return "value_mapping"
}

// KnowledgeConfigV1 represents knowledge_config
type KnowledgeConfigV1 struct {
	// Name 知识项名称，在同一个RunbookSet中必须唯一。
	Name string `json:"name" yaml:"name"`
	// DisplayName 知识项显示名称。
	DisplayName *SemanticStringV1 `json:"display_name" yaml:"display_name"`
	// ShortDescription 知识项简短描述。
	ShortDescription *SemanticStringV1 `json:"short_description" yaml:"short_description"`
	// Description 知识项详细描述信息。
	Description *SemanticStringV1 `json:"description,omitempty" yaml:"description,omitempty"`
	// ApplyPolicy 知识如何应用的配置。
	ApplyPolicy *KnowledgeConfigV1ApplyPolicy `json:"apply_policy" yaml:"apply_policy"`
	// ContentType 内容类型，支持markdown、html、url、pdf等。UModel 内置支持的类型为 markdown。
	ContentType string `json:"content_type" yaml:"content_type"`
	// Content 知识内容，根据content_type可以是文本内容或URL地址。
	Content string `json:"content,omitempty" yaml:"content,omitempty"`
	// ContentUrl 知识内容的外部URL地址。
	ContentUrl string `json:"content_url,omitempty" yaml:"content_url,omitempty"`
	// Priority 知识项优先级，用于排序显示以及模型推理时选择。
	Priority int64 `json:"priority,omitempty" yaml:"priority,omitempty"`
	// LastUpdated 最后更新时间。
	LastUpdated time.Time `json:"last_updated,omitempty" yaml:"last_updated,omitempty"`
	// Tags 知识项标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// Validate 验证KnowledgeConfigV1是否符合schema定义
func (s *KnowledgeConfigV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取KnowledgeConfigV1的类型标识
func (s *KnowledgeConfigV1) GetKind() string {
	return "knowledge_config"
}

// ActionConfigV1 represents action_config
type ActionConfigV1 struct {
	// Name 操作名称，在同一个RunbookSet中必须唯一。
	Name string `json:"name" yaml:"name"`
	// DisplayName 操作显示名称。
	DisplayName *SemanticStringV1 `json:"display_name" yaml:"display_name"`
	// ShortDescription 操作简短描述。
	ShortDescription *SemanticStringV1 `json:"short_description,omitempty" yaml:"short_description,omitempty"`
	// Description 操作详细描述信息。
	Description *SemanticStringV1 `json:"description,omitempty" yaml:"description,omitempty"`
	// ActionType 操作类型，例如pop_api、mcp、api_call、script、webhook等。
	ActionType string `json:"action_type" yaml:"action_type"`
	// Inputs 操作参数配置列表。
	Inputs []*ParameterConfigV1 `json:"inputs,omitempty" yaml:"inputs,omitempty"`
	// Outputs 操作输出配置列表。
	Outputs []*ParameterConfigV1 `json:"outputs,omitempty" yaml:"outputs,omitempty"`
	// ConfirmationRequired 是否需要确认才能执行操作。
	ConfirmationRequired bool `json:"confirmation_required,omitempty" yaml:"confirmation_required,omitempty"`
	// RiskLevel 操作的风险等级。
	RiskLevel string `json:"risk_level,omitempty" yaml:"risk_level,omitempty"`
	// Properties 详细配置信息，用于配置不同类型操作的详细信息
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Tags 操作标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// Validate 验证ActionConfigV1是否符合schema定义
func (s *ActionConfigV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ActionConfigV1的类型标识
func (s *ActionConfigV1) GetKind() string {
	return "action_config"
}

// ToolParameterConfigV1 represents tool_parameter_config
type ToolParameterConfigV1 struct {
	// Properties 参数属性定义，键为参数名称，值为参数定义对象。
	Properties map[string]interface{} `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Required 必填参数名称列表。
	Required []string `json:"required,omitempty" yaml:"required,omitempty"`
}

// Validate 验证ToolParameterConfigV1是否符合schema定义
func (s *ToolParameterConfigV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ToolParameterConfigV1的类型标识
func (s *ToolParameterConfigV1) GetKind() string {
	return "tool_parameter_config"
}

// ParameterConfigV1 represents parameter_config
type ParameterConfigV1 struct {
	// Name 参数名称。
	Name string `json:"name" yaml:"name"`
	// DisplayName 参数显示名称。
	DisplayName *SemanticStringV1 `json:"display_name,omitempty" yaml:"display_name,omitempty"`
	// Description 参数描述信息。
	Description *SemanticStringV1 `json:"description,omitempty" yaml:"description,omitempty"`
	// Type 参数类型。
	Type string `json:"type" yaml:"type"`
	// Required 是否为必填参数。
	Required bool `json:"required,omitempty" yaml:"required,omitempty"`
	// Default 参数默认值。
	Default string `json:"default,omitempty" yaml:"default,omitempty"`
}

// Validate 验证ParameterConfigV1是否符合schema定义
func (s *ParameterConfigV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ParameterConfigV1的类型标识
func (s *ParameterConfigV1) GetKind() string {
	return "parameter_config"
}

// MetricV1 represents metric
type MetricV1 struct {
	// Name 指标的名称。值不能为空。
	Name string `json:"name" yaml:"name"`
	// DisplayName 指标的显示名称。
	DisplayName *SemanticStringV1 `json:"display_name,omitempty" yaml:"display_name,omitempty"`
	// Description 指标的描述。值格式为语义字符串。
	Description *SemanticStringV1 `json:"description,omitempty" yaml:"description,omitempty"`
	// ShortDescription 指标的简短描述。值格式为语义字符串。
	ShortDescription *SemanticStringV1 `json:"short_description,omitempty" yaml:"short_description,omitempty"`
	// LaunchStage 元素的发布阶段。默认值为 preview。
	LaunchStage string `json:"launch_stage,omitempty" yaml:"launch_stage,omitempty"`
	// Unit 指标的单位，值格式为字符串。 注意：单位仅用于展示，不会进行格式转换，例如 ms 不会自动根据大小转换为 s。 最佳实践：首先配置 data_format ，在大部分可观测场景下，data_format 即可满足需求，unit 填写为空即可。 若不满...
	Unit string `json:"unit,omitempty" yaml:"unit,omitempty"`
	// DataFormat 指标的格式化方式，值格式为字符串。支持的格式化选项： 数值格式化： - KMB: 千、百万、十亿格式化，样例：K,Mil,Bil - milli: 处理为毫秒格式，样例：1,000,000 存储格式化： - byte: 处理为字节格式，样例：B/KB...
	DataFormat string `json:"data_format,omitempty" yaml:"data_format,omitempty"`
	// MaxValue 字段的最大值。值可以为空。仅适用于整数和浮点类型。
	MaxValue float64 `json:"max_value,omitempty" yaml:"max_value,omitempty"`
	// MinValue 字段的最小值。值可以为空。仅适用于整数和浮点类型。
	MinValue float64 `json:"min_value,omitempty" yaml:"min_value,omitempty"`
	// DefaultValue 字段的默认值。值可以为空。
	DefaultValue interface{} `json:"default_value,omitempty" yaml:"default_value,omitempty"`
	// Icon 用于表示该指标的图标。
	Icon string `json:"icon,omitempty" yaml:"icon,omitempty"`
	// Labels 用于表示该指标自身额外的标签。即在 MetricSet 的标签基础上，该指标还具有的额外标签。
	Labels []*FieldSpecV1 `json:"labels,omitempty" yaml:"labels,omitempty"`
	// GoldenMetric 是否为黄金指标。
	GoldenMetric bool `json:"golden_metric,omitempty" yaml:"golden_metric,omitempty"`
	// Generator 指标的生成方式，如果是 PromMode，该字段为 PromQL语句，能够执行并得到一个可直接使用的 Measure 类型指标。 例如：rate(request_count{}[1m])，在一些场景下结合 aggregator 字段，能够计算出聚合维...
	Generator string `json:"generator,omitempty" yaml:"generator,omitempty"`
	// Aggregator 指标的聚合方式。如果指标本身是聚合的，且聚合方式在多种维度组合下均一致，则不需要配置次字段，其他情况需要配置。一些示例场景如下： 1. Prometheus指标和Metric从时间线维度相同 1.1 rate(cpu_usage_seconds_to...
	Aggregator string `json:"aggregator,omitempty" yaml:"aggregator,omitempty"`
	// IntervalUs 指标的间隔，值格式为整数或整数数组，单位为微秒。 - 当为单个整数时：表示固定的采集间隔 - 当为整数数组时：表示多个采集间隔，用于支持不同精度的数据采集
	IntervalUs interface{} `json:"interval_us,omitempty" yaml:"interval_us,omitempty"`
	// Type 指标的类型。对于无需二次处理的指标，该字段应固定为 gauge。
	Type string `json:"type,omitempty" yaml:"type,omitempty"`
	// QueryMode 指标期望的查询模式。值必须是以下之一：range, instant, both。
	QueryMode string `json:"query_mode,omitempty" yaml:"query_mode,omitempty"`
	// DisplayType 指标的显示类型。当前未使用。
	DisplayType string `json:"display_type,omitempty" yaml:"display_type,omitempty"`
	// Statistics 生成该指标时的统计方式，即该指标有多种生成方式。当前仅在基础云监控场景下使用。
	Statistics []string `json:"statistics,omitempty" yaml:"statistics,omitempty"`
	// Tags 用于表示该指标的标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
	// Properties 用于表示该指标的附加属性。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// DefaultFillPolicy 指标的默认填充策略。 值可以是 null, 0, last, next。
	DefaultFillPolicy string `json:"default_fill_policy,omitempty" yaml:"default_fill_policy,omitempty"`
}

// Validate 验证MetricV1是否符合schema定义
func (s *MetricV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取MetricV1的类型标识
func (s *MetricV1) GetKind() string {
	return "metric"
}

// ObservationV1 represents observation
type ObservationV1 struct {
	// Name 观察名称，在同一个RunbookSet中必须唯一。
	Name string `json:"name" yaml:"name"`
	// DisplayName 观察显示名称。
	DisplayName *SemanticStringV1 `json:"display_name" yaml:"display_name"`
	// ShortDescription 观察简短描述。
	ShortDescription *SemanticStringV1 `json:"short_description" yaml:"short_description"`
	// Description 观察详细描述信息。
	Description *SemanticStringV1 `json:"description,omitempty" yaml:"description,omitempty"`
	// Phenomenon 现象定义，描述要观察什么以及如何观察。
	Phenomenon *ObservationV1Phenomenon `json:"phenomenon" yaml:"phenomenon"`
	// Conclusions 结论配置列表，根据现象观察结果进行判断。
	Conclusions []*ObservationV1ConclusionsItem `json:"conclusions" yaml:"conclusions"`
	// Properties 观察属性配置。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Tags 观察标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// Validate 验证ObservationV1是否符合schema定义
func (s *ObservationV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ObservationV1的类型标识
func (s *ObservationV1) GetKind() string {
	return "observation"
}

// MetadataV1 represents metadata
type MetadataV1 struct {
	// Name 元素在 UModel 系统中的名称。值不能为空。值格式为小写字母数字字符。
	Name string `json:"name" yaml:"name"`
	// DisplayName 元素在 UModel 系统中的显示名称。值不能为空。
	DisplayName *SemanticStringV1 `json:"display_name,omitempty" yaml:"display_name,omitempty"`
	// Description 元素在 UModel 系统中的描述。
	Description *SemanticStringV1 `json:"description,omitempty" yaml:"description,omitempty"`
	// ShortDescription 元素在 UModel系统中的简短描述。
	ShortDescription *SemanticStringV1 `json:"short_description,omitempty" yaml:"short_description,omitempty"`
	// Domain 域。值格式为'domain.domain'。可以以点连接。
	Domain string `json:"domain" yaml:"domain"`
	// LaunchStage 元素的发布阶段。默认值为 preview。
	LaunchStage string `json:"launch_stage,omitempty" yaml:"launch_stage,omitempty"`
	// Icon 元素在UModel系统中的图标。值格式为'url'。
	Icon string `json:"icon,omitempty" yaml:"icon,omitempty"`
	// Uri 用于表示该元素唯一标识。
	Uri string `json:"uri,omitempty" yaml:"uri,omitempty"`
	// Tags 用于表示该元素的标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
	// Properties 用于表示该元素的附加属性。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// CommonSchemaInfo 背景：在阿里云可观测业务使用中，内置的UModel数据会作为公共UModel（CommonSchema）默认存在，公共UModel数据以引用方式（CommonSchemaRef）配置在UModel，在查询时动态生成UModel实例并附加该字段作为额外...
	CommonSchemaInfo *MetadataV1CommonSchemaInfo `json:"common_schema_info,omitempty" yaml:"common_schema_info,omitempty"`
}

// Validate 验证MetadataV1是否符合schema定义
func (s *MetadataV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取MetadataV1的类型标识
func (s *MetadataV1) GetKind() string {
	return "metadata"
}

// SchemaV1 represents schema
type SchemaV1 struct {
	// Url Schema 的 URL。Core 部分都为 "umodel.aliyun.com"
	Url string `json:"url" yaml:"url"`
	// Version Schema 的版本。命名格式为 "v1.2.3"。
	Version string `json:"version" yaml:"version"`
}

// Validate 验证SchemaV1是否符合schema定义
func (s *SchemaV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取SchemaV1的类型标识
func (s *SchemaV1) GetKind() string {
	return "schema"
}

// TelemetryDataV1 represents telemetry_data
type TelemetryDataV1 struct {
	// Fields 可观测数据的字段列表。
	Fields []*FieldSpecV1 `json:"fields,omitempty" yaml:"fields,omitempty"`
	// TimeField 可观测数据的时间字段。一般要求时间字段为时间戳类型，支持秒、毫秒、微秒、纳秒。
	TimeField string `json:"time_field,omitempty" yaml:"time_field,omitempty"`
	// DisplayField 注意：定位和 `name_fields` 有一定重叠，字段已废弃，请使用 `name_fields` 字段第一个值替代。可观测数据的显示字段。即默认展示的字段。
	DisplayField string `json:"display_field,omitempty" yaml:"display_field,omitempty"`
	// NameFields 可观测数据的显示字段。建议按照显示重要性配置先后顺序，前端、算法等在各类场景会根据特点自由选择，例如极窄/引用场景下只取name_fields的第一个值。 例如：服务操作实体，建议取值为 ["operation_name", "service_nam...
	NameFields []string `json:"name_fields,omitempty" yaml:"name_fields,omitempty"`
	// HiddenFields 可观测数据的隐藏字段。即不用作展示的字段。
	HiddenFields []string `json:"hidden_fields,omitempty" yaml:"hidden_fields,omitempty"`
	// TagFields 可观测数据的标签字段。标签字段默认聚合在一起显示和分析。
	TagFields []string `json:"tag_fields,omitempty" yaml:"tag_fields,omitempty"`
	// OrderedFields 可观测数据的排序字段。即当前数据集的排序字段。
	OrderedFields []string `json:"ordered_fields,omitempty" yaml:"ordered_fields,omitempty"`
	// DefaultOrder 可观测数据的默认排序。默认值为 asc。
	DefaultOrder string `json:"default_order,omitempty" yaml:"default_order,omitempty"`
}

// Validate 验证TelemetryDataV1是否符合schema定义
func (s *TelemetryDataV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取TelemetryDataV1的类型标识
func (s *TelemetryDataV1) GetKind() string {
	return "telemetry_data"
}

// ToolV1 represents tool
type ToolV1 struct {
	// Name 工具名称，在同一个 Toolkit 内必须唯一。
	Name string `json:"name" yaml:"name"`
	// DisplayName 工具显示名称。
	DisplayName *SemanticStringV1 `json:"display_name" yaml:"display_name"`
	// ShortDescription 工具简短描述，LLM 用来决定是否调用此工具的关键信息。
	ShortDescription *SemanticStringV1 `json:"short_description,omitempty" yaml:"short_description,omitempty"`
	// Description 工具详细描述信息。
	Description *SemanticStringV1 `json:"description,omitempty" yaml:"description,omitempty"`
	// InputSchema 工具输入参数定义，JSON Schema 风格。
	InputSchema *ToolParameterConfigV1 `json:"input_schema,omitempty" yaml:"input_schema,omitempty"`
	// OutputSchema 工具输出参数定义，JSON Schema 风格。
	OutputSchema *ToolParameterConfigV1 `json:"output_schema,omitempty" yaml:"output_schema,omitempty"`
	// RiskLevel 操作的风险等级。
	RiskLevel string `json:"risk_level,omitempty" yaml:"risk_level,omitempty"`
	// Idempotent 操作是否幂等/可重入，重复执行结果一致。
	Idempotent bool `json:"idempotent,omitempty" yaml:"idempotent,omitempty"`
	// ConfirmationRequired 是否需要确认才能执行操作。
	ConfirmationRequired bool `json:"confirmation_required,omitempty" yaml:"confirmation_required,omitempty"`
	// Properties 工具级别的额外配置，可覆盖或补充 Toolkit 的 properties。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Tags 工具标签。
	Tags map[string]string `json:"tags,omitempty" yaml:"tags,omitempty"`
}

// Validate 验证ToolV1是否符合schema定义
func (s *ToolV1) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// GetKind 获取ToolV1的类型标识
func (s *ToolV1) GetKind() string {
	return "tool"
}

// ConstraintTypeV1Enum 枚举值列表
type ConstraintTypeV1Enum struct {
	Values []interface{} `json:"values,omitempty" yaml:"values,omitempty"`
	// DefaultValue 默认值
	DefaultValue string `json:"default_value,omitempty" yaml:"default_value,omitempty"`
}

// Validate 验证ConstraintTypeV1Enum是否符合schema定义
func (s *ConstraintTypeV1Enum) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// ConstraintTypeV1Array 数组约束定义，内部的 item 可以嵌套定义 metadata_properties，也支持特殊引用规则 "type_ref"。
type ConstraintTypeV1Array struct {
	Item    map[string]interface{} `json:"item,omitempty" yaml:"item,omitempty"`
	MinSize float64                `json:"min_size,omitempty" yaml:"min_size,omitempty"`
	MaxSize float64                `json:"max_size,omitempty" yaml:"max_size,omitempty"`
}

// Validate 验证ConstraintTypeV1Array是否符合schema定义
func (s *ConstraintTypeV1Array) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// ConstraintTypeV1AdvancedExpressionLeft 左操作数，可以是字段引用或字面值
type ConstraintTypeV1AdvancedExpressionLeft struct {
	Type string `json:"type,omitempty" yaml:"type,omitempty"`
	// Value 具体值或字段路径
	Value string `json:"value,omitempty" yaml:"value,omitempty"`
}

// Validate 验证ConstraintTypeV1AdvancedExpressionLeft是否符合schema定义
func (s *ConstraintTypeV1AdvancedExpressionLeft) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// ConstraintTypeV1AdvancedExpressionRight 右操作数，可以是字段引用或字面值
type ConstraintTypeV1AdvancedExpressionRight struct {
	Type string `json:"type,omitempty" yaml:"type,omitempty"`
	// Value 具体值或字段路径
	Value string `json:"value,omitempty" yaml:"value,omitempty"`
}

// Validate 验证ConstraintTypeV1AdvancedExpressionRight是否符合schema定义
func (s *ConstraintTypeV1AdvancedExpressionRight) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// ConstraintTypeV1AdvancedExpression 约束表达式，支持逻辑操作符和字段引用
type ConstraintTypeV1AdvancedExpression struct {
	// Operator 逻辑操作符
	Operator string `json:"operator,omitempty" yaml:"operator,omitempty"`
	// Conditions 条件列表，支持嵌套逻辑表达式
	Conditions []map[string]interface{} `json:"conditions,omitempty" yaml:"conditions,omitempty"`
	// Left 左操作数，可以是字段引用或字面值
	Left *ConstraintTypeV1AdvancedExpressionLeft `json:"left,omitempty" yaml:"left,omitempty"`
	// Right 右操作数，可以是字段引用或字面值
	Right *ConstraintTypeV1AdvancedExpressionRight `json:"right,omitempty" yaml:"right,omitempty"`
}

// Validate 验证ConstraintTypeV1AdvancedExpression是否符合schema定义
func (s *ConstraintTypeV1AdvancedExpression) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// ConstraintTypeV1Advanced 高级约束定义，用于支持更复杂的约束条件，包括逻辑操作和字段引用。 主要功能： 1. 支持逻辑操作符：and, or, not, eq, ne, gt, ge, lt, le, in, nin, exists, regex 2. 支持字段路径引用： -...
type ConstraintTypeV1Advanced struct {
	// Expression 约束表达式，支持逻辑操作符和字段引用
	Expression *ConstraintTypeV1AdvancedExpression `json:"expression,omitempty" yaml:"expression,omitempty"`
}

// Validate 验证ConstraintTypeV1Advanced是否符合schema定义
func (s *ConstraintTypeV1Advanced) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// AutomationConfigV1Trigger 触发条件配置。
type AutomationConfigV1Trigger struct {
	// TriggerType 触发条件类型，如 scheduled（定期触发）、event（事件触发）、custom（自定义触发）等。
	TriggerType string `json:"trigger_type" yaml:"trigger_type"`
	// Properties 触发条件相关属性配置，根据type类型自由扩展。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
}

// Validate 验证AutomationConfigV1Trigger是否符合schema定义
func (s *AutomationConfigV1Trigger) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// SkillConfigV1FilesItem inline struct
type SkillConfigV1FilesItem struct {
	// Name 文件名称，包含相对路径（如 SKILL.md、scripts/extract.py、references/REFERENCE.md）。
	Name string `json:"name" yaml:"name"`
	// Content 文件内容。
	Content string `json:"content" yaml:"content"`
}

// Validate 验证SkillConfigV1FilesItem是否符合schema定义
func (s *SkillConfigV1FilesItem) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// LinkV1Src 源 Set 的标识。值不能为空。
type LinkV1Src struct {
	// Domain 源 Set 的域。
	Domain string `json:"domain" yaml:"domain"`
	// Kind 源 Set 的类型。值不能为空。
	Kind string `json:"kind" yaml:"kind"`
	// Name 源 Set 的名称。值不能为空。
	Name string `json:"name" yaml:"name"`
	// Filter 对于源 Set 的过滤器，用于部分 Link 的场景，例如 EntitySet 中只有"region=cn-beijing"的实体存在此关联。该方式已废弃，请使用 filter_by_entity 替代。
	Filter string `json:"filter,omitempty" yaml:"filter,omitempty"`
}

// Validate 验证LinkV1Src是否符合schema定义
func (s *LinkV1Src) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// LinkV1Dest 目标 Set 的标识。值不能为空。
type LinkV1Dest struct {
	// Domain 目标 Set 的域。
	Domain string `json:"domain" yaml:"domain"`
	// Kind 目标 Set 的类型。值不能为空。
	Kind string `json:"kind" yaml:"kind"`
	// Name 目标 Set 的名称。值不能为空。
	Name string `json:"name" yaml:"name"`
}

// Validate 验证LinkV1Dest是否符合schema定义
func (s *LinkV1Dest) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// KnowledgeConfigV1ApplyPolicy 知识如何应用的配置。
type KnowledgeConfigV1ApplyPolicy struct {
	// ApplyType 应用策略，如auto（自动）、manual（手动）、always（总是）、custom（自定义）等。
	ApplyType string `json:"apply_type" yaml:"apply_type"`
	// Properties 应用相关属性配置，根据 custom 类型自由扩展。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
}

// Validate 验证KnowledgeConfigV1ApplyPolicy是否符合schema定义
func (s *KnowledgeConfigV1ApplyPolicy) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// ObservationV1Phenomenon 现象定义，描述要观察什么以及如何观察。
type ObservationV1Phenomenon struct {
	// PhenomenonType 现象类型，如query（查询）、action（动作）、dashboard（大盘）、event（事件）等。
	PhenomenonType string `json:"phenomenon_type" yaml:"phenomenon_type"`
	// Inputs 现象相关输入配置，用于指引上层如何选择默认的参数进行填入。包括 Dashboard 变量、Query 输入参数等
	Inputs []*ParameterConfigV1 `json:"inputs,omitempty" yaml:"inputs,omitempty"`
	// Outputs 可选，现象相关输出配置，用于指引上层如何解析查询结果。
	Outputs []*ParameterConfigV1 `json:"outputs,omitempty" yaml:"outputs,omitempty"`
	// Properties 现象相关属性配置，根据 type 类型自由扩展。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
}

// Validate 验证ObservationV1Phenomenon是否符合schema定义
func (s *ObservationV1Phenomenon) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// ObservationV1ConclusionsItem inline struct
type ObservationV1ConclusionsItem struct {
	// ConditionType 结论生效条件类型，根据现象类型，条件执行方式不同。可以是 query/action 执行结果后的 bool 表达式计算，也可以是由 LLM 进行判断的 prompts。
	ConditionType string `json:"condition_type" yaml:"condition_type"`
	// Condition 结论生效条件，根据现象类型，条件执行方式不同。
	Condition string `json:"condition" yaml:"condition"`
	// Severity 结论严重程度。
	Severity string `json:"severity" yaml:"severity"`
	// DisplayName 结论显示名称。
	DisplayName *SemanticStringV1 `json:"display_name" yaml:"display_name"`
	// ShortDescription 结论简短描述。
	ShortDescription *SemanticStringV1 `json:"short_description" yaml:"short_description"`
	// Description 结论详细描述。
	Description *SemanticStringV1 `json:"description,omitempty" yaml:"description,omitempty"`
	// Group 结论分组。在同一个结论分组下，只返回最高等级的结论。
	Group string `json:"group" yaml:"group"`
	// Properties 结论相关属性配置。
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
}

// Validate 验证ObservationV1ConclusionsItem是否符合schema定义
func (s *ObservationV1ConclusionsItem) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// MetadataV1CommonSchemaInfo 背景：在阿里云可观测业务使用中，内置的UModel数据会作为公共UModel（CommonSchema）默认存在，公共UModel数据以引用方式（CommonSchemaRef）配置在UModel，在查询时动态生成UModel实例并附加该字段作为额外...
type MetadataV1CommonSchemaInfo struct {
	// Group CommonSchema的Group信息
	Group string `json:"group,omitempty" yaml:"group,omitempty"`
	// Version CommonSchema的版本号
	Version string `json:"version,omitempty" yaml:"version,omitempty"`
}

// Validate 验证MetadataV1CommonSchemaInfo是否符合schema定义
func (s *MetadataV1CommonSchemaInfo) Validate() error {
	// TODO: 实现验证逻辑
	return nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = json.Marshal
	_ = time.Now
}
