// Code generated by schema_go_generator_v2.py. DO NOT EDIT.

// Package umodel provides Go SDK for UModel Schema
package umodel

import (
	"encoding/json"
	"fmt"
	"gopkg.in/yaml.v3"
	"io"
	"strings"
)

// Version SDK版本
const Version = "2.0.0"

// ParseJSON 从JSON数据解析UModel对象
func ParseJSON(data []byte, v interface{}) error {
	return json.Unmarshal(data, v)
}

// ParseYAML 从YAML数据解析UModel对象
func ParseYAML(data []byte, v interface{}) error {
	return yaml.Unmarshal(data, v)
}

// TypeRegistry 类型注册表，用于动态创建类型实例
var TypeRegistry = map[string]func() interface{}{
	"aliyun_prometheus:v1.0.0":  func() interface{} { return &AliyunPrometheusV100{} },
	"data_link:v1.0.0":          func() interface{} { return &DataLinkV100{} },
	"elasticsearch:v1.0.0":      func() interface{} { return &ElasticsearchV100{} },
	"entity_set:v1.0.0":         func() interface{} { return &EntitySetV100{} },
	"entity_set_link:v1.0.0":    func() interface{} { return &EntitySetLinkV100{} },
	"entity_source:v1.0.0":      func() interface{} { return &EntitySourceV100{} },
	"entity_source_link:v1.0.0": func() interface{} { return &EntitySourceLinkV100{} },
	"event_set:v1.0.0":          func() interface{} { return &EventSetV100{} },
	"explorer:v1.0.0":           func() interface{} { return &ExplorerV100{} },
	"explorer_link:v1.0.0":      func() interface{} { return &ExplorerLinkV100{} },
	"external_storage:v1.0.0":   func() interface{} { return &ExternalStorageV100{} },
	"log_set:v1.0.0":            func() interface{} { return &LogSetV100{} },
	"metric_set:v1.0.0":         func() interface{} { return &MetricSetV100{} },
	"mysql:v1.0.0":              func() interface{} { return &MysqlV100{} },
	"profile_set:v1.0.0":        func() interface{} { return &ProfileSetV100{} },
	"prometheus:v1.0.0":         func() interface{} { return &PrometheusV100{} },
	"runbook_link:v1.0.0":       func() interface{} { return &RunbookLinkV100{} },
	"runbook_set:v1.0.0":        func() interface{} { return &RunbookSetV100{} },
	"sls_entitystore:v1.0.0":    func() interface{} { return &SlsEntitystoreV100{} },
	"sls_logstore:v1.0.0":       func() interface{} { return &SlsLogstoreV100{} },
	"sls_metricstore:v1.0.0":    func() interface{} { return &SlsMetricstoreV100{} },
	"storage_link:v1.0.0":       func() interface{} { return &StorageLinkV100{} },
	"trace_set:v1.0.0":          func() interface{} { return &TraceSetV100{} },
}

// ParseType 根据类型名称解析对象
func ParseType(typeName string, data []byte, format string) (interface{}, error) {
	factory, ok := TypeRegistry[typeName]
	if !ok {
		return nil, fmt.Errorf("unknown type: %s", typeName)
	}

	obj := factory()
	switch format {
	case "json":
		err := json.Unmarshal(data, obj)
		return obj, err
	case "yaml":
		err := yaml.Unmarshal(data, obj)
		return obj, err
	default:
		return nil, fmt.Errorf("unsupported format: %s", format)
	}
}

// umodelHeader 用于预解析UModel对象的kind和schema信息，并进行基础校验
type umodelHeader struct {
	Kind     string `json:"kind" yaml:"kind"`
	Metadata struct {
		Domain string `json:"domain" yaml:"domain"`
		Name   string `json:"name" yaml:"name"`
	} `json:"metadata" yaml:"metadata"`
	Schema struct {
		Version string `json:"version" yaml:"version"`
	} `json:"schema" yaml:"schema"`
	Spec map[string]interface{} `json:"spec" yaml:"spec"`
}

// Valid 验证UModel对象的基础结构是否符合要求
func (h *umodelHeader) Valid() error {
	// 检查必要字段是否存在且非空
	if h.Kind == "" {
		return fmt.Errorf("missing required field: kind")
	}

	if h.Schema.Version == "" {
		return fmt.Errorf("missing required field: schema.version")
	}

	if h.Metadata.Domain == "" {
		return fmt.Errorf("missing required field: metadata.domain")
	}

	if h.Metadata.Name == "" {
		return fmt.Errorf("missing required field: metadata.name")
	}

	if h.Spec == nil {
		return fmt.Errorf("missing required field: spec")
	}

	if len(h.Spec) == 0 {
		return fmt.Errorf("spec field cannot be empty")
	}

	// spec 必须是非空的 JSON Object

	return nil
}

// ParseJsonUModel 从JSON数据自动解析UModel对象
func ParseJsonUModel(data []byte) (UModelCoreObject, error) {
	// 先解析header获取基础信息
	var header umodelHeader
	if err := json.Unmarshal(data, &header); err != nil {
		return nil, fmt.Errorf("failed to parse header: %w", err)
	}

	// 验证UModel基础结构
	if err := header.Valid(); err != nil {
		return nil, err
	}

	// 构建类型键
	typeKey := fmt.Sprintf("%s:%s", header.Kind, header.Schema.Version)

	// 查找类型工厂
	factory, ok := TypeRegistry[typeKey]
	if !ok {
		// 尝试查找兼容版本
		// 如果版本是v0.x.x，尝试v1.0.0
		if strings.HasPrefix(header.Schema.Version, "v0.") {
			altTypeKey := fmt.Sprintf("%s:v1.0.0", header.Kind)
			factory, ok = TypeRegistry[altTypeKey]
		}
		if !ok {
			return nil, fmt.Errorf("unknown type: %s (tried %s)", typeKey, typeKey)
		}
	}

	// 创建实例并解析
	obj := factory()
	if err := json.Unmarshal(data, obj); err != nil {
		return nil, fmt.Errorf("failed to parse object: %w", err)
	}

	// 转换为UModelCoreObject
	coreObj, ok := obj.(UModelCoreObject)
	if !ok {
		return nil, fmt.Errorf("object does not implement UModelCoreObject: %s", typeKey)
	}

	return coreObj, nil
}

// ParseYamlUModel 从YAML数据自动解析UModel对象
func ParseYamlUModel(data []byte) (UModelCoreObject, error) {
	// 先解析header获取基础信息
	var header umodelHeader
	if err := yaml.Unmarshal(data, &header); err != nil {
		return nil, fmt.Errorf("failed to parse header: %w", err)
	}

	// 验证UModel基础结构
	if err := header.Valid(); err != nil {
		return nil, err
	}

	// 构建类型键
	typeKey := fmt.Sprintf("%s:%s", header.Kind, header.Schema.Version)

	// 查找类型工厂
	factory, ok := TypeRegistry[typeKey]
	if !ok {
		// 尝试查找兼容版本
		// 如果版本是v0.x.x，尝试v1.0.0
		if strings.HasPrefix(header.Schema.Version, "v0.") {
			altTypeKey := fmt.Sprintf("%s:v1.0.0", header.Kind)
			factory, ok = TypeRegistry[altTypeKey]
		}
		if !ok {
			return nil, fmt.Errorf("unknown type: %s (tried %s)", typeKey, typeKey)
		}
	}

	// 创建实例并解析
	obj := factory()
	if err := yaml.Unmarshal(data, obj); err != nil {
		return nil, fmt.Errorf("failed to parse object: %w", err)
	}

	// 转换为UModelCoreObject
	coreObj, ok := obj.(UModelCoreObject)
	if !ok {
		return nil, fmt.Errorf("object does not implement UModelCoreObject: %s", typeKey)
	}

	return coreObj, nil
}

// IsCoreObject 判断对象是否实现了UModelCoreObject接口
func IsCoreObject(obj interface{}) bool {
	_, ok := obj.(UModelCoreObject)
	return ok
}

// IsLinkObject 判断对象是否实现了UModelLinkObject接口
func IsLinkObject(obj interface{}) bool {
	_, ok := obj.(UModelLinkObject)
	return ok
}

// GetObjectMetadata 获取任意UModel对象的Metadata（如果支持）
func GetObjectMetadata(obj interface{}) *MetadataV1 {
	if coreObj, ok := obj.(UModelCoreObject); ok {
		return coreObj.GetMetadata()
	}
	return nil
}

// GetObjectSchema 获取任意UModel对象的Schema（如果支持）
func GetObjectSchema(obj interface{}) *SchemaV1 {
	if coreObj, ok := obj.(UModelCoreObject); ok {
		return coreObj.GetSchema()
	}
	return nil
}

// GetLinkEndpoints 获取Link对象的源和目标端点（如果支持）
func GetLinkEndpoints(obj interface{}) (src, dest *LinkEndpoint) {
	if linkObj, ok := obj.(UModelLinkObject); ok {
		return linkObj.GetSrc(), linkObj.GetDest()
	}
	return nil, nil
}

// init 确保所有导入的包都被使用
func init() {
	_ = io.Discard
	_ = fmt.Sprintf
}
