kind: entity_set_link
schema:
  url: "umodel.aliyun.com"
  version: "v0.1.0"
metadata:
  name: "devops.pipeline_exec_devops.service"
  domain: devops
  display_name:
    en_us: "Pipeline Deploys Service"
    zh_cn: "流水线发布服务"
  description:
    en_us: "A pipeline builds or deploys a service."
    zh_cn: "流水线构建或发布服务。"
spec:
  src:
    domain: devops
    kind: entity_set
    name: devops.pipeline
  dest:
    domain: devops
    kind: entity_set
    name: devops.service
  entity_link_type: exec
